from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import JSON, DateTime, Enum, ForeignKey, Integer, String, Text, UniqueConstraint
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models.base import Base, CreatedAtMixin, TimestampMixin, UUIDPrimaryKeyMixin
from app.models.enums import ArtifactStatus


class Artifact(Base, UUIDPrimaryKeyMixin, TimestampMixin):
    """The deliverable a workflow node produces (e.g. a requirements doc).

    An artifact is a container: its actual content lives in
    `ArtifactVersion` rows (one per draft/edit), and `current_version`
    always points at the latest one. `status` is the artifact's own review
    lifecycle (see `ArtifactStatus`) — related to, but independent of, its
    owning `WorkflowNode`'s broader `WorkflowStatus`.
    """

    __tablename__ = "artifacts"

    project_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("projects.id", ondelete="CASCADE"), nullable=False)
    workflow_node_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("workflow_nodes.id", ondelete="CASCADE"), nullable=False
    )
    # Denormalized from workflow_node.story_id — set only for an artifact
    # produced inside a per-story delivery lane. See
    # app/services/graph_engine.py's resolve_required_inputs, which
    # filters by this so lanes never resolve each other's artifacts as a
    # shared "approved input."
    story_id: Mapped[uuid.UUID | None] = mapped_column(ForeignKey("stories.id", ondelete="CASCADE"), nullable=True)
    artifact_type: Mapped[str] = mapped_column(String(100), nullable=False)
    title: Mapped[str] = mapped_column(String(255), nullable=False)
    status: Mapped[ArtifactStatus] = mapped_column(
        Enum(ArtifactStatus, native_enum=False, length=20, validate_strings=True),
        default=ArtifactStatus.DRAFT,
        nullable=False,
    )
    created_by_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("users.id"), nullable=False)

    # Nullable + use_alter: an artifact can exist before it has a version,
    # and ArtifactVersion.artifact_id points back at this table, so the two
    # tables have a circular FK. use_alter/post_update tell SQLAlchemy to
    # create this FK in a second ALTER TABLE step and to update it after
    # the row insert, breaking the ordering deadlock.
    current_version_id: Mapped[uuid.UUID | None] = mapped_column(
        ForeignKey("artifact_versions.id", ondelete="SET NULL", use_alter=True, name="fk_artifacts_current_version_id"),
        nullable=True,
    )

    project: Mapped["Project"] = relationship("Project", back_populates="artifacts")
    workflow_node: Mapped["WorkflowNode"] = relationship("WorkflowNode", back_populates="artifacts")
    story: Mapped["Story | None"] = relationship("Story")
    created_by: Mapped["User"] = relationship("User", foreign_keys=[created_by_id])
    versions: Mapped[list["ArtifactVersion"]] = relationship(
        "ArtifactVersion",
        back_populates="artifact",
        cascade="all, delete-orphan",
        foreign_keys="ArtifactVersion.artifact_id",
        order_by="ArtifactVersion.version_number",
    )
    current_version: Mapped["ArtifactVersion | None"] = relationship(
        "ArtifactVersion", foreign_keys=[current_version_id], post_update=True
    )


class ArtifactVersion(Base, UUIDPrimaryKeyMixin, CreatedAtMixin):
    """One immutable snapshot of an artifact's content.

    `content_markdown` is the canonical human-readable content;
    `content_json` is an optional structured form (e.g. for a
    machine-editable form of the same artifact) — not every version has
    one. There is no agent-authorship link yet: AI drafting isn't wired up
    (see docs/mvp-plan.md), so every version is human-created for now via
    `created_by`. Re-add an optional agent-run link when that's built.
    """

    __tablename__ = "artifact_versions"
    __table_args__ = (UniqueConstraint("artifact_id", "version_number"),)

    artifact_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("artifacts.id", ondelete="CASCADE"), nullable=False)
    version_number: Mapped[int] = mapped_column(Integer, nullable=False)
    # "fullContent" — the canonical, complete document. Everything below is
    # a compression of this, generated by
    # app/services/artifact_summary.py's ArtifactSummaryResult whenever
    # this version's artifact is approved (see
    # app/api/routes/reviews.py's approve_review) — null until then, since
    # a not-yet-approved draft has no reason to be compressed for other
    # stages to consume yet.
    content_markdown: Mapped[str] = mapped_column(Text, nullable=False)
    content_json: Mapped[dict | None] = mapped_column(JSON, nullable=True)
    change_summary: Mapped[str | None] = mapped_column(Text, nullable=True)
    created_by_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("users.id"), nullable=False)

    # A few human sentences — for a person skimming, not for feeding back
    # into another agent call.
    executive_summary: Mapped[str | None] = mapped_column(Text, nullable=True)
    # What app/services/ai_generation.py's build_prioritized_context uses
    # by default instead of full_content (see its P2/P5 priority split) —
    # denser than executive_summary, meant to carry what a downstream agent
    # needs to build on this artifact correctly without reading it in full.
    agent_context_summary: Mapped[str | None] = mapped_column(Text, nullable=True)
    # Extracted, not inferred — see ArtifactSummaryResult's docstring: each
    # is only populated with things the document actually states.
    key_decisions: Mapped[list[str] | None] = mapped_column(JSON, nullable=True)
    open_questions: Mapped[list[str] | None] = mapped_column(JSON, nullable=True)
    risks: Mapped[list[str] | None] = mapped_column(JSON, nullable=True)
    # Null until the summaries above are (re)generated; set every time they
    # are, so a stale summary (e.g. from before a re-summarization change)
    # is distinguishable from a version that was never summarized at all.
    generated_summary_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)

    artifact: Mapped["Artifact"] = relationship(
        "Artifact", back_populates="versions", foreign_keys=[artifact_id]
    )
    created_by: Mapped["User"] = relationship("User", foreign_keys=[created_by_id])
    reviews: Mapped[list["Review"]] = relationship(
        "Review", back_populates="artifact_version", cascade="all, delete-orphan"
    )
