"""Mock AI generation — deterministic stand-in for a real model call.

Real generation now exists (see app/services/ai_generation.py), which calls
this module when ANTHROPIC_API_KEY isn't configured — so the system stays
fully testable, and demoable at zero cost, without a paid key. Output here
is deterministic and derived only from `agent_key` and the workflow
node/action. `estimate_mock_usage` produces token/cost numbers in the same
shape a real provider response has; the numbers themselves are just
placeholders, unlike ai_generation.py's real usage/cost figures.
"""

from app.models import AgentPromptRole, WorkflowNode
from app.services.retrieval import RetrievedChunk


def generate_mock_output(
    *,
    agent_key: str,
    node: WorkflowNode,
    action: AgentPromptRole,
    input_artifact_count: int,
    retrieved_chunks: list[RetrievedChunk] | None = None,
    iteration: int = 1,
    validation_feedback: list[str] | None = None,
) -> str:
    """`iteration`/`validation_feedback` let app/services/loop_engine.py's
    IMPROVE step produce a visibly different (and longer) draft each pass —
    without that, this deterministic generator would return byte-identical
    output every iteration, and the loop's quality score could never rise
    without a real model call. Each named piece of feedback gets its own
    "Addressed:" line, so the mock loop's improvement is genuinely legible,
    not just longer for its own sake."""
    retrieved_chunks = retrieved_chunks or []
    if retrieved_chunks:
        source_titles = ", ".join(dict.fromkeys(c.source_title for c in retrieved_chunks))
        knowledge_note = f"It also had {len(retrieved_chunks)} relevant internal knowledge excerpt(s) available, from: {source_titles} (Source: {retrieved_chunks[0].source_title})."
    else:
        knowledge_note = "No relevant internal knowledge was found, so this draft relies on project context alone."

    content = (
        f"# {node.name} — Mock Output\n\n"
        f"_Generated by `{agent_key}` performing `{action.value}` — no real AI model is connected yet "
        f"(see docs/mvp-plan.md). This placeholder stands in for the `{node.output_artifact_type}` "
        f"artifact this stage produces._\n\n"
        f"This draft would normally be based on {input_artifact_count} input artifact(s) "
        f"and the stage's active prompt. {knowledge_note}\n\n"
        f"Replace this service with a real model call once one is wired up.\n"
    )

    if iteration > 1:
        content += f"\n## Revision history (loop iteration {iteration})\n\n"
        if validation_feedback:
            content += "This revision addresses the previous iteration's validation feedback:\n\n"
            for item in validation_feedback:
                content += f"- **Addressed:** {item}\n"
        content += (
            f"\nThis is the iteration-{iteration} revision of this mock draft — each pass through "
            "the loop adds further detail here to simulate a real model incorporating feedback and "
            "producing a more complete draft on each improvement pass.\n"
        )

    return content


def estimate_mock_usage(*, prompt_text: str, output_text: str) -> tuple[dict, float]:
    """Word-count-based stand-in for real tokenization — not an accurate
    token count, just a plausible, deterministic number in the right shape.
    `cost` uses an arbitrary placeholder rate, not any real model's pricing."""
    prompt_tokens = len(prompt_text.split())
    completion_tokens = len(output_text.split())
    total_tokens = prompt_tokens + completion_tokens

    _PLACEHOLDER_RATE_PER_TOKEN = 0.000002  # not a real price — arbitrary, for shape only
    cost = round(total_tokens * _PLACEHOLDER_RATE_PER_TOKEN, 6)

    token_usage = {
        "prompt_tokens": prompt_tokens,
        "completion_tokens": completion_tokens,
        "total_tokens": total_tokens,
    }
    return token_usage, cost
