"""Mock AI generation — deterministic stand-in for a real model call.

Real generation now exists (see app/services/ai_generation.py), which calls
this module when ANTHROPIC_API_KEY isn't configured — so the system stays
fully testable, and demoable at zero cost, without a paid key. Output here
is deterministic and derived only from `agent_key` and the workflow
node/action. `estimate_mock_usage` produces token/cost numbers in the same
shape a real provider response has; the numbers themselves are just
placeholders, unlike ai_generation.py's real usage/cost figures.
"""

from app.models import AgentPromptRole, WorkflowNode


def generate_mock_output(*, agent_key: str, node: WorkflowNode, action: AgentPromptRole, input_artifact_count: int) -> str:
    return (
        f"# {node.name} — Mock Output\n\n"
        f"_Generated by `{agent_key}` performing `{action.value}` — no real AI model is connected yet "
        f"(see docs/mvp-plan.md). This placeholder stands in for the `{node.output_artifact_type}` "
        f"artifact this stage produces._\n\n"
        f"This draft would normally be based on {input_artifact_count} input artifact(s) "
        f"and the stage's active prompt. Replace this service with a real model call once one is wired up.\n"
    )


def estimate_mock_usage(*, prompt_text: str, output_text: str) -> tuple[dict, float]:
    """Word-count-based stand-in for real tokenization — not an accurate
    token count, just a plausible, deterministic number in the right shape.
    `cost` uses an arbitrary placeholder rate, not any real model's pricing."""
    prompt_tokens = len(prompt_text.split())
    completion_tokens = len(output_text.split())
    total_tokens = prompt_tokens + completion_tokens

    _PLACEHOLDER_RATE_PER_TOKEN = 0.000002  # not a real price — arbitrary, for shape only
    cost = round(total_tokens * _PLACEHOLDER_RATE_PER_TOKEN, 6)

    token_usage = {
        "prompt_tokens": prompt_tokens,
        "completion_tokens": completion_tokens,
        "total_tokens": total_tokens,
    }
    return token_usage, cost
