"""RepoBootstrapService — turns a brand-new, genuinely EMPTY GitHub
repository into a real, runnable starter project, using this project's
own already-approved documents and Project Engineering Setup (technology
stack) as the source of truth — not a fresh model call. See
app/api/routes/repo_bootstrap.py for the one endpoint that calls this.

Deliberately deterministic, template-based scaffolding — no LLM call
anywhere in this module. Mirrors app/services/repo_context_builder.py's
own reasoning for staying non-AI: which starter files a known framework
needs is a mechanical fact, not a judgment call, and a scaffold a human
is about to build real work on top of should never be something a model
might hallucinate wrong.

HARD RULE, and the one deliberate, narrow exception to
app/services/github_integration.py's "never write to a repository's
default branch" invariant (see that module's own docstring): GitHub's
Contents API has no way to open a PR into a base branch that does not
exist yet, and a genuinely empty repository has NO branch at all — its
default branch is only a name until the first commit lands. There is
therefore no way to bootstrap an empty repository through this
codebase's normal branch+PR flow; the very first commit MUST be made
directly against the repository's configured default_branch, which is
exactly what creates it. This module's own bootstrap_repository is the
ONLY caller in this codebase allowed to do that, and only after the
caller (see the route) has independently re-verified the repository is
still empty immediately before writing.

FRAMEWORK REGISTRY: backend frameworks are looked up in _BACKEND_TEMPLATES
below rather than a hand-written if/elif chain — adding real boilerplate
for a new backend framework means adding one BackendTemplate entry there
(markers to match, whether it's a JS/TS workspace member, and a build
function), and generate_scaffold_files/README/.gitignore/workspace-root
generation all pick it up automatically. The frontend side stays a single
if-check (has_frontend) since, as of this module, Next.js is the only
frontend template — the same registry shape can grow a
_FRONTEND_TEMPLATES list the same way if/when a second one is added.
"""

from __future__ import annotations

from collections.abc import Callable
from dataclasses import dataclass, field

from sqlalchemy.orm import Session

from app.models import (
    Artifact,
    ArtifactStatus,
    CodingStandardCategory,
    Project,
    ProjectCodingStandard,
    ProjectEngineeringSetup,
    Repository,
)
from app.services import github_integration as github_api

# --- Framework detection -------------------------------------------------------------
# Free-text fields (app/models/project_engineering_setup.py) — matched by
# substring, case-insensitively, against the handful of stacks this module
# actually knows how to scaffold for real. Anything else falls back to the
# generic skeleton below rather than fabricating boilerplate for a
# framework this module has never actually verified.

_NEXTJS_MARKERS = ("next.js", "nextjs", "next")
_FASTAPI_MARKERS = ("fastapi", "fast api")
_EXPRESS_MARKERS = ("express",)  # matches "Express", "Express.js", "Node.js (Express)", ...
_TYPESCRIPT_MARKERS = ("typescript",)  # checked against primary_language, same substring convention


def _matches(value: str | None, markers: tuple[str, ...]) -> bool:
    if not value:
        return False
    lowered = value.lower()
    return any(marker in lowered for marker in markers)


@dataclass
class ScaffoldFile:
    path: str
    content: str


def _gitignore(*, has_node: bool, has_python: bool) -> str:
    sections = ["# Generated by RepoBootstrapService — see docs/HLD.md for the design this scaffold implements.\n"]
    if has_node:
        sections.append(
            "# Node\nnode_modules/\n.next/\nout/\ndist/\nbuild/\n.env.local\n.env*.local\nnpm-debug.log*\nyarn-debug.log*\nyarn-error.log*\n"
        )
    if has_python:
        sections.append(
            "# Python\n__pycache__/\n*.pyc\n.venv/\nvenv/\n.env\n.pytest_cache/\n*.egg-info/\ndist/\nbuild/\n"
        )
    sections.append("# Editors/OS\n.vscode/\n.idea/\n.DS_Store\nThumbs.db\n")
    return "\n".join(sections)


def _readme(
    project: Project,
    setup: ProjectEngineeringSetup,
    *,
    has_frontend_scaffold: bool,
    has_backend_scaffold: bool,
    backend_framework_name: str | None,
    workspace_members: list[str],
    has_solution_doc: bool,
    has_coding_standards: bool,
) -> str:
    stack_lines = [f"- **Application type:** {setup.application_type}", f"- **Primary language:** {setup.primary_language}"]
    if setup.frontend_framework:
        stack_lines.append(f"- **Frontend:** {setup.frontend_framework}")
    if setup.backend_framework:
        stack_lines.append(f"- **Backend:** {setup.backend_framework}")
    if setup.database:
        stack_lines.append(f"- **Database:** {setup.database}")
    if setup.cloud_provider:
        stack_lines.append(f"- **Cloud provider:** {setup.cloud_provider}")

    # A repository, not a pair of unrelated repositories that happen to be
    # committed together — this section is what makes "single workspace"
    # explicit to a human opening the repo for the first time, rather than
    # something only implied by two folders sitting side by side.
    layout_lines = [
        "This repository is a single workspace for this project — one place for every part of it, not "
        "separate repos per component:"
    ]
    if has_frontend_scaffold:
        layout_lines.append("- `frontend/` — the application's frontend.")
    if has_backend_scaffold:
        layout_lines.append("- `backend/` — the application's backend.")
    if not has_frontend_scaffold and not has_backend_scaffold:
        layout_lines.append(
            "- `src/` — placeholder; this project's Technology Stack doesn't match a framework this scaffold "
            "generates real boilerplate for yet (see `docs/HLD.md` for the intended architecture)."
        )
    layout_lines.append("- `docs/` — this project's own approved design documents, carried over as-is.")
    if has_coding_standards:
        layout_lines.append(
            "- `docs/CODING_STANDARDS.md` — this project's coding standards and agent guardrails, exactly as "
            "configured in Project Engineering Setup, so they travel with the code instead of staying only "
            "inside the platform."
        )
    if workspace_members:
        joined = " and ".join(f"`{member}/`" for member in workspace_members)
        layout_lines.append(
            f"- `package.json` (root) — a single npm workspace tying {joined} together: install and run each "
            "from the repository root, not only from inside its own folder."
        )

    run_lines = []
    if has_frontend_scaffold:
        run_lines.append("### Frontend (`frontend/`)\n```bash\ncd frontend\nnpm install\nnpm run dev\n```")
    if has_backend_scaffold:
        if backend_framework_name == "Express":
            run_lines.append("### Backend (`backend/`)\n```bash\ncd backend\nnpm install\nnpm run dev\n```")
        else:
            run_lines.append(
                "### Backend (`backend/`)\n```bash\ncd backend\npython -m venv .venv\n.venv/Scripts/activate  # .venv/bin/activate on macOS/Linux\npip install -r requirements.txt\nuvicorn app.main:app --reload\n```"
            )
    run_section = "\n\n".join(run_lines) if run_lines else (
        "This project's Technology Stack (above) doesn't match a framework this scaffold generates real "
        "boilerplate for yet — see `docs/HLD.md` for the intended architecture and start from there."
    )

    doc_links = ["[`docs/HLD.md`](docs/HLD.md)"]
    if has_solution_doc:
        doc_links.append("[`docs/SOLUTION_DISCOVERY.md`](docs/SOLUTION_DISCOVERY.md)")
    if has_coding_standards:
        doc_links.append("[`docs/CODING_STANDARDS.md`](docs/CODING_STANDARDS.md)")

    return (
        f"# {project.name}\n\n"
        f"{project.description or 'No description was recorded for this project.'}\n\n"
        "## Technology Stack\n\n" + "\n".join(stack_lines) + "\n\n"
        "## Workspace layout\n\n" + "\n".join(layout_lines) + "\n\n"
        "## Getting Started\n\n" + run_section + "\n\n"
        "## Documentation\n\n"
        "This repository was bootstrapped from the project's own approved design documents and configuration — "
        "see " + ", ".join(doc_links) + " for the full design and standards this scaffold implements.\n\n"
        "_This README and starter layout were generated automatically by Agentic SDLC Hub's repository "
        "bootstrap action, from this project's Project Engineering Setup and approved documents — not "
        "hand-written._\n"
    )


_CODING_STANDARD_CATEGORY_HEADINGS: dict[CodingStandardCategory, str] = {
    CodingStandardCategory.GENERAL: "General",
    CodingStandardCategory.ARCHITECTURE: "Architecture",
    CodingStandardCategory.SECURITY: "Security",
    CodingStandardCategory.TESTING: "Testing",
    CodingStandardCategory.GIT: "Git & Version Control",
    CodingStandardCategory.DOCUMENTATION: "Documentation",
}

# Fixed display order regardless of order_index/insertion order, so the
# generated doc always reads the same way project to project.
_CODING_STANDARD_CATEGORY_ORDER = [
    CodingStandardCategory.GENERAL,
    CodingStandardCategory.ARCHITECTURE,
    CodingStandardCategory.SECURITY,
    CodingStandardCategory.TESTING,
    CodingStandardCategory.GIT,
    CodingStandardCategory.DOCUMENTATION,
]


def _coding_standards_doc(setup: ProjectEngineeringSetup) -> str | None:
    """Human-readable docs/CODING_STANDARDS.md — the same project/company
    coding standards and agent guardrails that Agent Context Builder
    already injects into every agent run (see
    app/services/agent_context_builder.py), now also committed into the
    repository itself so a human contributor — or any tool reading this
    repository directly, not through the platform — has the same source
    of truth without opening Agentic SDLC Hub. Returns None when neither
    is configured, so callers can skip adding an empty file."""
    if not setup.coding_standards and not setup.guardrails:
        return None

    sections = [
        "# Coding Standards\n",
        "These are this project's coding standards and agent guardrails, exactly as configured in Agentic SDLC "
        "Hub's Project Engineering Setup. They are the same rules every AI agent working on this project is "
        "given as context — this file exists so a human contributor (or any tool reading this repository "
        "directly) has the same source of truth without opening the platform.\n",
    ]

    if setup.coding_standards:
        by_category: dict[CodingStandardCategory, list[ProjectCodingStandard]] = {}
        for standard in setup.coding_standards:
            by_category.setdefault(standard.category, []).append(standard)
        for category in _CODING_STANDARD_CATEGORY_ORDER:
            standards = by_category.get(category)
            if not standards:
                continue
            sections.append(f"## {_CODING_STANDARD_CATEGORY_HEADINGS[category]}\n")
            for standard in standards:
                sections.append(f"### {standard.title}\n\n{standard.content}\n")

    if setup.guardrails:
        sections.append("## Agent Guardrails\n")
        sections.append(
            "Rules every AI agent working on this project must follow, regardless of what a specific task "
            "asks for:\n"
        )
        for guardrail in setup.guardrails:
            sections.append(f"- {guardrail.rule_text}")

    sections.append(
        "\n_Generated automatically by Agentic SDLC Hub's repository bootstrap action from this project's "
        "Project Engineering Setup — edit standards and guardrails there so this file and every agent's "
        "context stay in sync; a manual edit here will not travel back to the platform._\n"
    )
    return "\n".join(sections)


def _root_workspace_package_json(project: Project, *, workspace_members: list[str]) -> str:
    """A workspace-root package.json — what actually makes the JS/TS
    members of this repo (frontend/, and now backend/ when the backend
    itself is JS/TS — see BackendTemplate.is_node_workspace) a single
    installable/runnable workspace rather than folders that just happen
    to share a repository: `npm install` and `npm run dev:<member>` both
    work from the repository root. Only called when workspace_members is
    non-empty; a Python backend (FastAPI) has nothing an npm workspace
    manifest can manage, which is why it keeps its own separate venv/pip
    flow (see the README's Getting Started section) instead of being
    forced in here.

    Also the fix for a real failure mode: app/services/code_runner.py's
    _resolve_test_command_cwd runs a configured "npm test"/"npm run
    build"/"npm run lint" command from the workspace ROOT whenever a root
    package.json exists (or when more than one subfolder has one, which is
    exactly this repo's shape once both frontend/ and a Node backend/
    exist) — so root scripts named test/build/lint must exist or that
    project's default Build/Test Commands fail immediately with npm's
    "Missing script" error on a freshly bootstrapped repo, before a human
    ever writes a line of code. `--workspaces --if-present` forwards each
    to whichever member actually defines it (see _nextjs_scaffold's and
    _express_scaffold's own placeholder "test"/"lint" scripts) and never
    errors on a member that doesn't."""
    workspace_list = ",\n".join(f'    "{member}"' for member in workspace_members)

    scripts: dict[str, str] = {}
    for member in workspace_members:
        scripts[f"dev:{member}"] = f"npm run dev --workspace {member}"
        scripts[f"build:{member}"] = f"npm run build --workspace {member}"
    if len(workspace_members) > 1:
        scripts["dev"] = " & ".join(f"npm run dev:{member}" for member in workspace_members)
    else:
        scripts["dev"] = f"npm run dev --workspace {workspace_members[0]}"
    # Root-level forwards for whatever a project's Build/Test Commands
    # (Project Engineering Setup, Step 9) are likely to invoke — see the
    # docstring above for why these three specifically must exist here.
    scripts["build"] = "npm run build --workspaces --if-present"
    scripts["test"] = "npm test --workspaces --if-present"
    scripts["lint"] = "npm run lint --workspaces --if-present"
    scripts_list = ",\n".join(f'    "{key}": "{value}"' for key, value in scripts.items())

    return (
        "{\n"
        f'  "name": "{_slug(project.name)}",\n'
        '  "private": true,\n'
        '  "workspaces": [\n'
        f"{workspace_list}\n"
        "  ],\n"
        '  "scripts": {\n'
        f"{scripts_list}\n"
        "  }\n"
        "}\n"
    )


def _nextjs_scaffold(project: Project) -> list[ScaffoldFile]:
    package_json = f"""{{
  "name": "{_slug(project.name)}-frontend",
  "version": "0.1.0",
  "private": true,
  "scripts": {{
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint",
    "test": "echo \\"No frontend tests configured yet — see docs/HLD.md\\""
  }},
  "dependencies": {{
    "next": "14.2.35",
    "react": "18.3.1",
    "react-dom": "18.3.1"
  }},
  "devDependencies": {{
    "@types/node": "20.14.0",
    "@types/react": "18.3.1",
    "@types/react-dom": "18.3.1",
    "typescript": "5.5.4",
    "tailwindcss": "3.4.10",
    "postcss": "8.4.41",
    "autoprefixer": "10.4.20"
  }}
}}
"""
    tsconfig = """{
  "compilerOptions": {
    "target": "ES2017",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "paths": { "@/*": ["./*"] }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx"],
  "exclude": ["node_modules"]
}
"""
    return [
        ScaffoldFile("frontend/package.json", package_json),
        ScaffoldFile("frontend/tsconfig.json", tsconfig),
        ScaffoldFile(
            "frontend/next.config.mjs",
            "/** @type {import('next').NextConfig} */\nconst nextConfig = {};\n\nexport default nextConfig;\n",
        ),
        ScaffoldFile(
            "frontend/tailwind.config.ts",
            "import type { Config } from \"tailwindcss\";\n\n"
            "const config: Config = {\n  content: [\"./app/**/*.{ts,tsx}\"],\n  theme: { extend: {} },\n  plugins: [],\n};\n\n"
            "export default config;\n",
        ),
        ScaffoldFile(
            "frontend/postcss.config.mjs",
            "export default {\n  plugins: { tailwindcss: {}, autoprefixer: {} },\n};\n",
        ),
        ScaffoldFile(
            "frontend/app/globals.css",
            "@tailwind base;\n@tailwind components;\n@tailwind utilities;\n",
        ),
        ScaffoldFile(
            "frontend/app/layout.tsx",
            "import \"./globals.css\";\n\n"
            f'export const metadata = {{ title: "{project.name}" }};\n\n'
            "export default function RootLayout({ children }: { children: React.ReactNode }) {\n"
            "  return (\n    <html lang=\"en\">\n      <body>{children}</body>\n    </html>\n  );\n}\n",
        ),
        ScaffoldFile(
            "frontend/app/page.tsx",
            f'export default function Home() {{\n  return (\n    <main style={{{{ padding: "2rem" }}}}>\n'
            f'      <h1>{project.name}</h1>\n      <p>Scaffolded starter — see the repository README.</p>\n'
            "    </main>\n  );\n}\n",
        ),
    ]


def _fastapi_scaffold(project: Project) -> list[ScaffoldFile]:
    return [
        ScaffoldFile(
            "backend/requirements.txt",
            "fastapi>=0.111,<1\nuvicorn[standard]>=0.30,<1\npydantic>=2.7,<3\n",
        ),
        ScaffoldFile("backend/app/__init__.py", ""),
        ScaffoldFile(
            "backend/app/main.py",
            "from fastapi import FastAPI\n\n"
            f'app = FastAPI(title="{project.name}")\n\n\n'
            '@app.get("/health")\ndef health() -> dict:\n    return {"status": "ok"}\n\n\n'
            '@app.get("/")\ndef root() -> dict:\n'
            f'    return {{"message": "{project.name} — scaffolded starter, see the repository README."}}\n',
        ),
    ]


def _express_scaffold(project: Project, setup: ProjectEngineeringSetup) -> list[ScaffoldFile]:
    """Real Express starter — the same fidelity as _fastapi_scaffold's
    FastAPI template. Uses TypeScript when this project's primary
    language says so (same substring-marker convention framework
    detection already uses above); plain JavaScript otherwise, since
    "Node.js (Express)" alone doesn't say which."""
    use_ts = _matches(setup.primary_language, _TYPESCRIPT_MARKERS)
    slug = _slug(project.name)
    message = f"{project.name} — scaffolded starter, see the repository README."

    if use_ts:
        package_json = f"""{{
  "name": "{slug}-backend",
  "version": "0.1.0",
  "private": true,
  "scripts": {{
    "dev": "ts-node-dev --respawn --transpile-only src/index.ts",
    "build": "tsc",
    "start": "node dist/index.js",
    "test": "echo \\"No backend tests configured yet — see docs/HLD.md\\"",
    "lint": "echo \\"No backend lint configured yet — see docs/HLD.md\\""
  }},
  "dependencies": {{
    "express": "4.19.2",
    "cors": "2.8.5",
    "dotenv": "16.4.5"
  }},
  "devDependencies": {{
    "typescript": "5.5.4",
    "ts-node-dev": "2.0.0",
    "@types/express": "4.17.21",
    "@types/node": "20.14.0",
    "@types/cors": "2.8.17"
  }}
}}
"""
        tsconfig = """{
  "compilerOptions": {
    "target": "ES2020",
    "module": "commonjs",
    "outDir": "dist",
    "rootDir": "src",
    "strict": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "resolveJsonModule": true
  },
  "include": ["src/**/*.ts"]
}
"""
        index_ts = (
            'import express from "express";\n'
            'import cors from "cors";\n'
            'import "dotenv/config";\n'
            'import { healthRouter } from "./routes/health";\n\n'
            "const app = express();\n"
            "app.use(cors());\n"
            "app.use(express.json());\n"
            'app.use("/health", healthRouter);\n\n'
            'app.get("/", (_req, res) => {\n'
            f'  res.json({{ message: "{message}" }});\n'
            "});\n\n"
            "const port = process.env.PORT || 4000;\n"
            "app.listen(port, () => {\n"
            "  console.log(`Server listening on port ${port}`);\n"
            "});\n"
        )
        health_ts = (
            'import { Router } from "express";\n\n'
            "export const healthRouter = Router();\n\n"
            'healthRouter.get("/", (_req, res) => {\n'
            '  res.json({ status: "ok" });\n'
            "});\n"
        )
        files = [
            ScaffoldFile("backend/package.json", package_json),
            ScaffoldFile("backend/tsconfig.json", tsconfig),
            ScaffoldFile("backend/src/index.ts", index_ts),
            ScaffoldFile("backend/src/routes/health.ts", health_ts),
        ]
    else:
        package_json = f"""{{
  "name": "{slug}-backend",
  "version": "0.1.0",
  "private": true,
  "scripts": {{
    "dev": "node --watch src/index.js",
    "start": "node src/index.js",
    "test": "echo \\"No backend tests configured yet — see docs/HLD.md\\"",
    "lint": "echo \\"No backend lint configured yet — see docs/HLD.md\\""
  }},
  "dependencies": {{
    "express": "4.19.2",
    "cors": "2.8.5",
    "dotenv": "16.4.5"
  }},
  "devDependencies": {{
    "nodemon": "3.1.4"
  }}
}}
"""
        index_js = (
            'const express = require("express");\n'
            'const cors = require("cors");\n'
            'require("dotenv").config();\n'
            'const healthRouter = require("./routes/health");\n\n'
            "const app = express();\n"
            "app.use(cors());\n"
            "app.use(express.json());\n"
            'app.use("/health", healthRouter);\n\n'
            'app.get("/", (_req, res) => {\n'
            f'  res.json({{ message: "{message}" }});\n'
            "});\n\n"
            "const port = process.env.PORT || 4000;\n"
            "app.listen(port, () => {\n"
            "  console.log(`Server listening on port ${port}`);\n"
            "});\n"
        )
        health_js = (
            'const { Router } = require("express");\n\n'
            "const healthRouter = Router();\n\n"
            'healthRouter.get("/", (_req, res) => {\n'
            '  res.json({ status: "ok" });\n'
            "});\n\n"
            "module.exports = healthRouter;\n"
        )
        files = [
            ScaffoldFile("backend/package.json", package_json),
            ScaffoldFile("backend/src/index.js", index_js),
            ScaffoldFile("backend/src/routes/health.js", health_js),
        ]

    files.append(ScaffoldFile("backend/.env.example", "PORT=4000\n"))
    return files


@dataclass(frozen=True)
class BackendTemplate:
    """One backend framework this module can scaffold real boilerplate
    for. Add a new backend by adding one of these to _BACKEND_TEMPLATES —
    generate_scaffold_files, the README, .gitignore, and workspace-root
    generation all pick it up with no further changes.

    `is_node_workspace` marks a JS/TS backend (Express, and any future
    Node-based one) so it (a) is folded into the root npm workspace
    alongside frontend/, and (b) contributes to .gitignore's Node section
    rather than its Python one — the opposite of a Python backend like
    FastAPI, which keeps its own separate venv/pip flow outside the JS
    workspace entirely."""

    name: str
    markers: tuple[str, ...]
    is_node_workspace: bool
    build: Callable[[Project, ProjectEngineeringSetup], list[ScaffoldFile]]


_BACKEND_TEMPLATES: list[BackendTemplate] = [
    BackendTemplate(name="FastAPI", markers=_FASTAPI_MARKERS, is_node_workspace=False, build=lambda project, setup: _fastapi_scaffold(project)),
    BackendTemplate(name="Express", markers=_EXPRESS_MARKERS, is_node_workspace=True, build=_express_scaffold),
]


def _match_backend_template(setup: ProjectEngineeringSetup) -> BackendTemplate | None:
    value = setup.backend_framework
    if not value:
        return None
    lowered = value.lower()
    for template in _BACKEND_TEMPLATES:
        if any(marker in lowered for marker in template.markers):
            return template
    return None


def _slug(name: str) -> str:
    return "".join(c.lower() if c.isalnum() else "-" for c in name).strip("-") or "project"


def _latest_approved_content(db: Session, project: Project, artifact_type: str) -> str | None:
    artifact = (
        db.query(Artifact)
        .filter(Artifact.project_id == project.id, Artifact.artifact_type == artifact_type, Artifact.status == ArtifactStatus.APPROVED)
        .order_by(Artifact.updated_at.desc())
        .first()
    )
    if artifact is None or artifact.current_version is None:
        return None
    return artifact.current_version.content_markdown


def generate_scaffold_files(db: Session, *, project: Project, setup: ProjectEngineeringSetup) -> list[ScaffoldFile]:
    """The full set of files a bootstrap commit writes — deterministic
    given `project`/`setup`/this project's currently-approved documents.
    Never touches GitHub; a pure, independently-testable function."""
    has_frontend = _matches(setup.frontend_framework, _NEXTJS_MARKERS)
    backend_template = _match_backend_template(setup)
    has_backend = backend_template is not None
    backend_is_node = bool(backend_template and backend_template.is_node_workspace)
    hld_content = _latest_approved_content(db, project, "hld_document")
    solution_content = _latest_approved_content(db, project, "solution_options_doc")
    standards_content = _coding_standards_doc(setup)

    workspace_members: list[str] = []
    if has_frontend:
        workspace_members.append("frontend")
    if backend_is_node:
        workspace_members.append("backend")

    files: list[ScaffoldFile] = [
        ScaffoldFile(
            "README.md",
            _readme(
                project, setup, has_frontend_scaffold=has_frontend, has_backend_scaffold=has_backend,
                backend_framework_name=backend_template.name if backend_template else None,
                workspace_members=workspace_members,
                has_solution_doc=solution_content is not None, has_coding_standards=standards_content is not None,
            ),
        ),
        ScaffoldFile(
            ".gitignore",
            _gitignore(has_node=has_frontend or backend_is_node, has_python=has_backend and not backend_is_node),
        ),
    ]

    if has_frontend:
        files += _nextjs_scaffold(project)
    if backend_template is not None:
        files += backend_template.build(project, setup)
    if not has_frontend and not has_backend:
        # Generic fallback — no framework this module knows how to scaffold
        # for real; still give the repo a sane starting layout rather than
        # nothing beyond README/.gitignore.
        files.append(ScaffoldFile("src/.gitkeep", ""))

    if workspace_members:
        # Workspace root — see _root_workspace_package_json's docstring for
        # why this is what actually makes these folders one workspace.
        files.append(ScaffoldFile("package.json", _root_workspace_package_json(project, workspace_members=workspace_members)))

    if hld_content:
        files.append(ScaffoldFile("docs/HLD.md", hld_content))
    if solution_content:
        files.append(ScaffoldFile("docs/SOLUTION_DISCOVERY.md", solution_content))
    if standards_content:
        # This project's own coding standards + agent guardrails, carried
        # into the repository itself — see _coding_standards_doc's
        # docstring for why this matters beyond what Agent Context Builder
        # already injects invisibly at runtime.
        files.append(ScaffoldFile("docs/CODING_STANDARDS.md", standards_content))

    return files


class RepoBootstrapError(Exception):
    """A precondition failed before any GitHub write was attempted, or a
    real GitHubIntegrationError occurred partway through — the caller
    (see the route) turns this into an HTTP error either way. Some files
    may already have been committed when this is raised partway through
    `push_scaffold` (see its own docstring) — `commits` on this exception
    reports exactly which, so a caller can tell "nothing happened" apart
    from "the repo is now partially bootstrapped"."""

    def __init__(self, message: str, *, commits: list["BootstrapCommit"] | None = None):
        super().__init__(message)
        self.commits = commits or []


@dataclass
class BootstrapCommit:
    path: str
    commit_sha: str


@dataclass
class BootstrapResult:
    branch: str
    commits: list[BootstrapCommit] = field(default_factory=list)


def push_scaffold(token: str, repository: Repository, files: list[ScaffoldFile]) -> BootstrapResult:
    """Writes every scaffold file as its own commit, directly on
    `repository.default_branch` (see this module's HARD RULE above for
    why that's correct here and nowhere else). Each file is created
    (never updated — a genuinely empty repo has nothing to update) via
    the exact same github_integration.create_or_update_file GitHub
    already uses for every other write in this codebase; nothing here
    talks to GitHub any differently, only *where* it's allowed to write.

    Stops at the first failure and raises RepoBootstrapError carrying
    whatever commits already landed — a caller can't accidentally retry
    into duplicate commits (GitHub would reject a second create at the
    same path with no `sha`), and the repository is left in a real,
    inspectable state either way, never silently half-done with no
    record of what happened."""
    branch = repository.default_branch or "main"
    commits: list[BootstrapCommit] = []
    for f in files:
        try:
            commit_sha = github_api.create_or_update_file(
                token, repository.owner, repository.name, f.path,
                content=f.content, message=f"Bootstrap: add {f.path}", branch=branch,
            )
        except github_api.GitHubIntegrationError as exc:
            raise RepoBootstrapError(f"Failed writing {f.path}: {exc}", commits=commits) from exc
        commits.append(BootstrapCommit(path=f.path, commit_sha=commit_sha))
    return BootstrapResult(branch=branch, commits=commits)
