"""RepoBootstrapService — turns a brand-new, genuinely EMPTY GitHub
repository into a real, runnable starter project, using this project's
own already-approved documents and Project Engineering Setup (technology
stack) as the source of truth — not a fresh model call. See
app/api/routes/repo_bootstrap.py for the one endpoint that calls this.

Deliberately deterministic, template-based scaffolding — no LLM call
anywhere in this module. Mirrors app/services/repo_context_builder.py's
own reasoning for staying non-AI: which starter files a known framework
needs is a mechanical fact, not a judgment call, and a scaffold a human
is about to build real work on top of should never be something a model
might hallucinate wrong.

HARD RULE, and the one deliberate, narrow exception to
app/services/github_integration.py's "never write to a repository's
default branch" invariant (see that module's own docstring): GitHub's
Contents API has no way to open a PR into a base branch that does not
exist yet, and a genuinely empty repository has NO branch at all — its
default branch is only a name until the first commit lands. There is
therefore no way to bootstrap an empty repository through this
codebase's normal branch+PR flow; the very first commit MUST be made
directly against the repository's configured default_branch, which is
exactly what creates it. This module's own bootstrap_repository is the
ONLY caller in this codebase allowed to do that, and only after the
caller (see the route) has independently re-verified the repository is
still empty immediately before writing.
"""

from __future__ import annotations

from dataclasses import dataclass, field

from sqlalchemy.orm import Session

from app.models import Artifact, ArtifactStatus, Project, ProjectEngineeringSetup, Repository
from app.services import github_integration as github_api

# --- Framework detection -------------------------------------------------------------
# Free-text fields (app/models/project_engineering_setup.py) — matched by
# substring, case-insensitively, against the handful of stacks this module
# actually knows how to scaffold for real. Anything else falls back to the
# generic skeleton below rather than fabricating boilerplate for a
# framework this module has never actually verified.

_NEXTJS_MARKERS = ("next.js", "nextjs", "next")
_FASTAPI_MARKERS = ("fastapi", "fast api")


def _matches(value: str | None, markers: tuple[str, ...]) -> bool:
    if not value:
        return False
    lowered = value.lower()
    return any(marker in lowered for marker in markers)


@dataclass
class ScaffoldFile:
    path: str
    content: str


def _gitignore(*, has_node: bool, has_python: bool) -> str:
    sections = ["# Generated by RepoBootstrapService — see docs/HLD.md for the design this scaffold implements.\n"]
    if has_node:
        sections.append(
            "# Node\nnode_modules/\n.next/\nout/\nbuild/\n.env.local\n.env*.local\nnpm-debug.log*\nyarn-debug.log*\nyarn-error.log*\n"
        )
    if has_python:
        sections.append(
            "# Python\n__pycache__/\n*.pyc\n.venv/\nvenv/\n.env\n.pytest_cache/\n*.egg-info/\ndist/\nbuild/\n"
        )
    sections.append("# Editors/OS\n.vscode/\n.idea/\n.DS_Store\nThumbs.db\n")
    return "\n".join(sections)


def _readme(
    project: Project, setup: ProjectEngineeringSetup, *, has_frontend_scaffold: bool, has_backend_scaffold: bool, has_solution_doc: bool
) -> str:
    stack_lines = [f"- **Application type:** {setup.application_type}", f"- **Primary language:** {setup.primary_language}"]
    if setup.frontend_framework:
        stack_lines.append(f"- **Frontend:** {setup.frontend_framework}")
    if setup.backend_framework:
        stack_lines.append(f"- **Backend:** {setup.backend_framework}")
    if setup.database:
        stack_lines.append(f"- **Database:** {setup.database}")
    if setup.cloud_provider:
        stack_lines.append(f"- **Cloud provider:** {setup.cloud_provider}")

    run_lines = []
    if has_frontend_scaffold:
        run_lines.append("### Frontend (`frontend/`)\n```bash\ncd frontend\nnpm install\nnpm run dev\n```")
    if has_backend_scaffold:
        run_lines.append(
            "### Backend (`backend/`)\n```bash\ncd backend\npython -m venv .venv\n.venv/Scripts/activate  # .venv/bin/activate on macOS/Linux\npip install -r requirements.txt\nuvicorn app.main:app --reload\n```"
        )
    run_section = "\n\n".join(run_lines) if run_lines else (
        "This project's Technology Stack (above) doesn't match a framework this scaffold generates real "
        "boilerplate for yet — see `docs/HLD.md` for the intended architecture and start from there."
    )

    return (
        f"# {project.name}\n\n"
        f"{project.description or 'No description was recorded for this project.'}\n\n"
        "## Technology Stack\n\n" + "\n".join(stack_lines) + "\n\n"
        "## Getting Started\n\n" + run_section + "\n\n"
        "## Documentation\n\n"
        "This repository was bootstrapped from the project's own approved design documents — see "
        "[`docs/HLD.md`](docs/HLD.md)"
        + (" and [`docs/SOLUTION_DISCOVERY.md`](docs/SOLUTION_DISCOVERY.md)" if has_solution_doc else "")
        + " for the full design this scaffold implements.\n\n"
        "_This README and starter layout were generated automatically by Agentic SDLC Hub's repository "
        "bootstrap action, from this project's Project Engineering Setup and approved documents — not "
        "hand-written._\n"
    )


def _nextjs_scaffold(project: Project) -> list[ScaffoldFile]:
    package_json = f"""{{
  "name": "{_slug(project.name)}-frontend",
  "version": "0.1.0",
  "private": true,
  "scripts": {{
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  }},
  "dependencies": {{
    "next": "14.2.35",
    "react": "18.3.1",
    "react-dom": "18.3.1"
  }},
  "devDependencies": {{
    "@types/node": "20.14.0",
    "@types/react": "18.3.1",
    "@types/react-dom": "18.3.1",
    "typescript": "5.5.4",
    "tailwindcss": "3.4.10",
    "postcss": "8.4.41",
    "autoprefixer": "10.4.20"
  }}
}}
"""
    tsconfig = """{
  "compilerOptions": {
    "target": "ES2017",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "paths": { "@/*": ["./*"] }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx"],
  "exclude": ["node_modules"]
}
"""
    return [
        ScaffoldFile("frontend/package.json", package_json),
        ScaffoldFile("frontend/tsconfig.json", tsconfig),
        ScaffoldFile(
            "frontend/next.config.mjs",
            "/** @type {import('next').NextConfig} */\nconst nextConfig = {};\n\nexport default nextConfig;\n",
        ),
        ScaffoldFile(
            "frontend/tailwind.config.ts",
            "import type { Config } from \"tailwindcss\";\n\n"
            "const config: Config = {\n  content: [\"./app/**/*.{ts,tsx}\"],\n  theme: { extend: {} },\n  plugins: [],\n};\n\n"
            "export default config;\n",
        ),
        ScaffoldFile(
            "frontend/postcss.config.mjs",
            "export default {\n  plugins: { tailwindcss: {}, autoprefixer: {} },\n};\n",
        ),
        ScaffoldFile(
            "frontend/app/globals.css",
            "@tailwind base;\n@tailwind components;\n@tailwind utilities;\n",
        ),
        ScaffoldFile(
            "frontend/app/layout.tsx",
            "import \"./globals.css\";\n\n"
            f'export const metadata = {{ title: "{project.name}" }};\n\n'
            "export default function RootLayout({ children }: { children: React.ReactNode }) {\n"
            "  return (\n    <html lang=\"en\">\n      <body>{children}</body>\n    </html>\n  );\n}\n",
        ),
        ScaffoldFile(
            "frontend/app/page.tsx",
            f'export default function Home() {{\n  return (\n    <main style={{{{ padding: "2rem" }}}}>\n'
            f'      <h1>{project.name}</h1>\n      <p>Scaffolded starter — see the repository README.</p>\n'
            "    </main>\n  );\n}\n",
        ),
    ]


def _fastapi_scaffold(project: Project) -> list[ScaffoldFile]:
    return [
        ScaffoldFile(
            "backend/requirements.txt",
            "fastapi>=0.111,<1\nuvicorn[standard]>=0.30,<1\npydantic>=2.7,<3\n",
        ),
        ScaffoldFile("backend/app/__init__.py", ""),
        ScaffoldFile(
            "backend/app/main.py",
            "from fastapi import FastAPI\n\n"
            f'app = FastAPI(title="{project.name}")\n\n\n'
            '@app.get("/health")\ndef health() -> dict:\n    return {"status": "ok"}\n\n\n'
            '@app.get("/")\ndef root() -> dict:\n'
            f'    return {{"message": "{project.name} — scaffolded starter, see the repository README."}}\n',
        ),
    ]


def _slug(name: str) -> str:
    return "".join(c.lower() if c.isalnum() else "-" for c in name).strip("-") or "project"


def _latest_approved_content(db: Session, project: Project, artifact_type: str) -> str | None:
    artifact = (
        db.query(Artifact)
        .filter(Artifact.project_id == project.id, Artifact.artifact_type == artifact_type, Artifact.status == ArtifactStatus.APPROVED)
        .order_by(Artifact.updated_at.desc())
        .first()
    )
    if artifact is None or artifact.current_version is None:
        return None
    return artifact.current_version.content_markdown


def generate_scaffold_files(db: Session, *, project: Project, setup: ProjectEngineeringSetup) -> list[ScaffoldFile]:
    """The full set of files a bootstrap commit writes — deterministic
    given `project`/`setup`/this project's currently-approved documents.
    Never touches GitHub; a pure, independently-testable function."""
    has_frontend = _matches(setup.frontend_framework, _NEXTJS_MARKERS)
    has_backend = _matches(setup.backend_framework, _FASTAPI_MARKERS)
    hld_content = _latest_approved_content(db, project, "hld_document")
    solution_content = _latest_approved_content(db, project, "solution_options_doc")

    files: list[ScaffoldFile] = [
        ScaffoldFile(
            "README.md",
            _readme(
                project, setup, has_frontend_scaffold=has_frontend, has_backend_scaffold=has_backend,
                has_solution_doc=solution_content is not None,
            ),
        ),
        ScaffoldFile(".gitignore", _gitignore(has_node=has_frontend, has_python=has_backend)),
    ]

    if has_frontend:
        files += _nextjs_scaffold(project)
    if has_backend:
        files += _fastapi_scaffold(project)
    if not has_frontend and not has_backend:
        # Generic fallback — no framework this module knows how to scaffold
        # for real; still give the repo a sane starting layout rather than
        # nothing beyond README/.gitignore.
        files.append(ScaffoldFile("src/.gitkeep", ""))

    if hld_content:
        files.append(ScaffoldFile("docs/HLD.md", hld_content))
    if solution_content:
        files.append(ScaffoldFile("docs/SOLUTION_DISCOVERY.md", solution_content))

    return files


class RepoBootstrapError(Exception):
    """A precondition failed before any GitHub write was attempted, or a
    real GitHubIntegrationError occurred partway through — the caller
    (see the route) turns this into an HTTP error either way. Some files
    may already have been committed when this is raised partway through
    `push_scaffold` (see its own docstring) — `commits` on this exception
    reports exactly which, so a caller can tell "nothing happened" apart
    from "the repo is now partially bootstrapped"."""

    def __init__(self, message: str, *, commits: list["BootstrapCommit"] | None = None):
        super().__init__(message)
        self.commits = commits or []


@dataclass
class BootstrapCommit:
    path: str
    commit_sha: str


@dataclass
class BootstrapResult:
    branch: str
    commits: list[BootstrapCommit] = field(default_factory=list)


def push_scaffold(token: str, repository: Repository, files: list[ScaffoldFile]) -> BootstrapResult:
    """Writes every scaffold file as its own commit, directly on
    `repository.default_branch` (see this module's HARD RULE above for
    why that's correct here and nowhere else). Each file is created
    (never updated — a genuinely empty repo has nothing to update) via
    the exact same github_integration.create_or_update_file GitHub
    already uses for every other write in this codebase; nothing here
    talks to GitHub any differently, only *where* it's allowed to write.

    Stops at the first failure and raises RepoBootstrapError carrying
    whatever commits already landed — a caller can't accidentally retry
    into duplicate commits (GitHub would reject a second create at the
    same path with no `sha`), and the repository is left in a real,
    inspectable state either way, never silently half-done with no
    record of what happened."""
    branch = repository.default_branch or "main"
    commits: list[BootstrapCommit] = []
    for f in files:
        try:
            commit_sha = github_api.create_or_update_file(
                token, repository.owner, repository.name, f.path,
                content=f.content, message=f"Bootstrap: add {f.path}", branch=branch,
            )
        except github_api.GitHubIntegrationError as exc:
            raise RepoBootstrapError(f"Failed writing {f.path}: {exc}", commits=commits) from exc
        commits.append(BootstrapCommit(path=f.path, commit_sha=commit_sha))
    return BootstrapResult(branch=branch, commits=commits)
