"""test runs

Revision ID: 0820af90af5f
Revises: dc71869b2411
Create Date: 2026-08-31 12:20:10.690807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0820af90af5f'
down_revision: Union[str, None] = 'dc71869b2411'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_runs',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('workflow_node_id', sa.Uuid(), nullable=False),
    sa.Column('implementation_task_id', sa.Uuid(), nullable=False),
    sa.Column('implementation_run_id', sa.Uuid(), nullable=False),
    sa.Column('pull_request_link_id', sa.Uuid(), nullable=True),
    sa.Column('artifact_id', sa.Uuid(), nullable=True),
    sa.Column('artifact_version_id', sa.Uuid(), nullable=True),
    sa.Column('triggered_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('agent_type', sa.Enum('UNIT', 'API', 'UI', 'REGRESSION', 'SECURITY', name='testagenttype', native_enum=False, length=20), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='testrunstatus', native_enum=False, length=20), nullable=False),
    sa.Column('test_plan', sa.Text(), nullable=False),
    sa.Column('tests_to_add', sa.JSON(), nullable=False),
    sa.Column('tests_executed', sa.JSON(), nullable=False),
    sa.Column('pass_count', sa.Integer(), nullable=False),
    sa.Column('fail_count', sa.Integer(), nullable=False),
    sa.Column('bugs_found', sa.JSON(), nullable=False),
    sa.Column('suggested_fixes', sa.JSON(), nullable=False),
    sa.Column('coverage_impact', sa.JSON(), nullable=False),
    sa.Column('used_mock', sa.Boolean(), nullable=False),
    sa.Column('token_usage', sa.JSON(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.id'], name=op.f('fk_test_runs_artifact_id_artifacts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['artifact_version_id'], ['artifact_versions.id'], name=op.f('fk_test_runs_artifact_version_id_artifact_versions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['implementation_run_id'], ['implementation_runs.id'], name=op.f('fk_test_runs_implementation_run_id_implementation_runs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['implementation_task_id'], ['implementation_tasks.id'], name=op.f('fk_test_runs_implementation_task_id_implementation_tasks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_test_runs_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pull_request_link_id'], ['pull_request_links.id'], name=op.f('fk_test_runs_pull_request_link_id_pull_request_links'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['triggered_by_user_id'], ['users.id'], name=op.f('fk_test_runs_triggered_by_user_id_users')),
    sa.ForeignKeyConstraint(['workflow_node_id'], ['workflow_nodes.id'], name=op.f('fk_test_runs_workflow_node_id_workflow_nodes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_test_runs'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_runs')
    # ### end Alembic commands ###
