"""jira integration

Revision ID: 0f1ce2a8f5d0
Revises: fb79b6f9cf31
Create Date: 2026-08-31 22:21:34.136098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f1ce2a8f5d0'
down_revision: Union[str, None] = 'fb79b6f9cf31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jira_project_links',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('connection_id', sa.Uuid(), nullable=False),
    sa.Column('jira_project_key', sa.String(length=50), nullable=False),
    sa.Column('jira_project_name', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['integration_connections.id'], name=op.f('fk_jira_project_links_connection_id_integration_connections')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_jira_project_links_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jira_project_links')),
    sa.UniqueConstraint('project_id', name=op.f('uq_jira_project_links_project_id'))
    )
    op.create_table('jira_issue_links',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('jira_project_link_id', sa.Uuid(), nullable=False),
    sa.Column('source_type', sa.Enum('EPIC', 'STORY', 'IMPLEMENTATION_TASK', 'TESTING_BUG', name='jirasourcetype', native_enum=False, length=30), nullable=False),
    sa.Column('source_key', sa.String(length=500), nullable=False),
    sa.Column('source_label', sa.String(length=500), nullable=False),
    sa.Column('jira_issue_key', sa.String(length=50), nullable=False),
    sa.Column('jira_issue_type', sa.String(length=50), nullable=False),
    sa.Column('jira_issue_url', sa.String(length=500), nullable=False),
    sa.Column('parent_jira_issue_key', sa.String(length=50), nullable=True),
    sa.Column('jira_status', sa.String(length=100), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('triggered_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['jira_project_link_id'], ['jira_project_links.id'], name=op.f('fk_jira_issue_links_jira_project_link_id_jira_project_links'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_jira_issue_links_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['triggered_by_user_id'], ['users.id'], name=op.f('fk_jira_issue_links_triggered_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jira_issue_links')),
    sa.UniqueConstraint('jira_project_link_id', 'source_type', 'source_key', name=op.f('uq_jira_issue_links_jira_project_link_id_source_type_source_key'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jira_issue_links')
    op.drop_table('jira_project_links')
    # ### end Alembic commands ###
