"""sprint planning

Revision ID: 115697daea96
Revises: e928051fc407
Create Date: 2026-09-02 08:13:12.628060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '115697daea96'
down_revision: Union[str, None] = 'e928051fc407'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sprint_stories',
    sa.Column('sprint_id', sa.Uuid(), nullable=False),
    sa.Column('story_id', sa.Uuid(), nullable=False),
    sa.Column('planned_points', sa.Integer(), nullable=True),
    sa.Column('assigned_owner_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('PLANNED', 'IN_PROGRESS', 'DONE', 'REMOVED', name='sprintstorystatus', native_enum=False, length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_owner_id'], ['users.id'], name=op.f('fk_sprint_stories_assigned_owner_id_users')),
    sa.ForeignKeyConstraint(['sprint_id'], ['sprints.id'], name=op.f('fk_sprint_stories_sprint_id_sprints'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], name=op.f('fk_sprint_stories_story_id_stories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sprint_stories')),
    sa.UniqueConstraint('sprint_id', 'story_id', name=op.f('uq_sprint_stories_sprint_id_story_id'))
    )
    # NOTE: server_default added by hand — `sprints` already has rows.
    op.add_column('sprints', sa.Column('goal', sa.Text(), nullable=False, server_default=''))
    op.alter_column('sprints', 'goal', server_default=None)
    op.add_column('sprints', sa.Column('start_date', sa.Date(), nullable=True))
    op.add_column('sprints', sa.Column('end_date', sa.Date(), nullable=True))
    op.add_column('sprints', sa.Column('capacity_points', sa.Integer(), nullable=True))
    # DATA MIGRATION: SprintStatus renamed PLANNING -> PLANNED (and added
    # CANCELLED) — see app/models/enums.py. This is a plain-string
    # (native_enum=False) column, so autogenerate can't detect the rename
    # itself; any existing 'PLANNING' row must be rewritten by hand or it
    # fails Python-side enum validation on next read.
    op.execute("UPDATE sprints SET status = 'PLANNED' WHERE status = 'PLANNING'")
    # NOTE: autogenerate also proposed re-creating
    # 'fk_stories_source_artifact_version_id' and
    # 'fk_story_delivery_lanes_current_node_id' here — the same known
    # false-positive with use_alter=True FKs seen in earlier migrations
    # this session; both constraints already exist, so both are dropped
    # from this migration.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE sprints SET status = 'PLANNING' WHERE status = 'PLANNED'")
    op.drop_column('sprints', 'capacity_points')
    op.drop_column('sprints', 'end_date')
    op.drop_column('sprints', 'start_date')
    op.drop_column('sprints', 'goal')
    op.drop_table('sprint_stories')
    # ### end Alembic commands ###
