"""initial schema

Revision ID: 32e7ae2e6ed5
Revises: 
Create Date: 2026-08-29 22:47:40.536694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32e7ae2e6ed5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_definitions',
    sa.Column('agent_key', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_definitions')),
    sa.UniqueConstraint('agent_key', name=op.f('uq_agent_definitions_agent_key'))
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('agent_prompts',
    sa.Column('agent_definition_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('DRAFT', 'IMPROVE', 'VALIDATE', name='agentpromptrole', native_enum=False, length=20), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('template', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['agent_definition_id'], ['agent_definitions.id'], name=op.f('fk_agent_prompts_agent_definition_id_agent_definitions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_prompts')),
    sa.UniqueConstraint('agent_definition_id', 'role', 'version', name=op.f('uq_agent_prompts_agent_definition_id_role_version'))
    )
    op.create_table('projects',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('workflow_template_id', sa.String(length=100), nullable=False),
    sa.Column('workflow_template_version', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'ARCHIVED', name='projectstatus', native_enum=False, length=20), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_projects_created_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects'))
    )
    op.create_table('project_members',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'CONTRIBUTOR', 'APPROVER', 'VIEWER', name='projectrole', native_enum=False, length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_members_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_project_members_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_members')),
    sa.UniqueConstraint('project_id', 'user_id', name=op.f('uq_project_members_project_id_user_id'))
    )
    op.create_table('workflow_nodes',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('node_key', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('agent_key', sa.String(length=100), nullable=False),
    sa.Column('required_inputs', sa.JSON(), nullable=False),
    sa.Column('output_artifact_type', sa.String(length=100), nullable=False),
    sa.Column('requires_human_approval', sa.Boolean(), nullable=False),
    sa.Column('allowed_actions', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'WAITING_FOR_REVIEW', 'APPROVED', 'NEEDS_CHANGES', 'REJECTED', 'BLOCKED', 'COMPLETED', 'FAILED', name='workflowstatus', native_enum=False, length=30), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('position_x', sa.Float(), nullable=False),
    sa.Column('position_y', sa.Float(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_workflow_nodes_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_nodes')),
    sa.UniqueConstraint('project_id', 'node_key', name=op.f('uq_workflow_nodes_project_id_node_key'))
    )
    op.create_table('agent_runs',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('workflow_node_id', sa.Uuid(), nullable=False),
    sa.Column('agent_definition_id', sa.Uuid(), nullable=False),
    sa.Column('agent_prompt_id', sa.Uuid(), nullable=True),
    sa.Column('triggered_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.Enum('DRAFT', 'IMPROVE', 'VALIDATE', name='agentpromptrole', native_enum=False, length=20), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='agentrunstatus', native_enum=False, length=20), nullable=False),
    sa.Column('input_context', sa.JSON(), nullable=False),
    sa.Column('output_text', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['agent_definition_id'], ['agent_definitions.id'], name=op.f('fk_agent_runs_agent_definition_id_agent_definitions')),
    sa.ForeignKeyConstraint(['agent_prompt_id'], ['agent_prompts.id'], name=op.f('fk_agent_runs_agent_prompt_id_agent_prompts')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_agent_runs_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['triggered_by_user_id'], ['users.id'], name=op.f('fk_agent_runs_triggered_by_user_id_users')),
    sa.ForeignKeyConstraint(['workflow_node_id'], ['workflow_nodes.id'], name=op.f('fk_agent_runs_workflow_node_id_workflow_nodes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_runs'))
    )
    op.create_table('artifacts',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('workflow_node_id', sa.Uuid(), nullable=False),
    sa.Column('artifact_type', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'WAITING_FOR_REVIEW', 'APPROVED', 'NEEDS_CHANGES', 'REJECTED', 'BLOCKED', 'COMPLETED', 'FAILED', name='workflowstatus', native_enum=False, length=30), nullable=False),
    sa.Column('current_version_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    # current_version_id's FK is added below, via a separate ALTER TABLE,
    # once artifact_versions exists (artifacts <-> artifact_versions is a
    # circular reference: artifact_versions.artifact_id also points back
    # at this table). Postgres validates FK targets at CREATE TABLE time,
    # so this can't be declared inline here the way autogenerate first
    # emitted it.
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_artifacts_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_node_id'], ['workflow_nodes.id'], name=op.f('fk_artifacts_workflow_node_id_workflow_nodes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_artifacts'))
    )
    op.create_table('workflow_edges',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('source_node_id', sa.Uuid(), nullable=False),
    sa.Column('target_node_id', sa.Uuid(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_workflow_edges_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_node_id'], ['workflow_nodes.id'], name=op.f('fk_workflow_edges_source_node_id_workflow_nodes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_node_id'], ['workflow_nodes.id'], name=op.f('fk_workflow_edges_target_node_id_workflow_nodes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_edges'))
    )
    op.create_table('artifact_versions',
    sa.Column('artifact_id', sa.Uuid(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_format', sa.String(length=30), nullable=False),
    sa.Column('change_summary', sa.Text(), nullable=True),
    sa.Column('authored_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('authored_by_agent_run_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('authored_by_user_id IS NOT NULL OR authored_by_agent_run_id IS NOT NULL', name=op.f('ck_artifact_versions_has_author')),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.id'], name=op.f('fk_artifact_versions_artifact_id_artifacts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['authored_by_agent_run_id'], ['agent_runs.id'], name=op.f('fk_artifact_versions_authored_by_agent_run_id_agent_runs')),
    sa.ForeignKeyConstraint(['authored_by_user_id'], ['users.id'], name=op.f('fk_artifact_versions_authored_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_artifact_versions')),
    sa.UniqueConstraint('artifact_id', 'version_number', name=op.f('uq_artifact_versions_artifact_id_version_number'))
    )
    op.create_table('audit_logs',
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('actor_agent_run_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['actor_agent_run_id'], ['agent_runs.id'], name=op.f('fk_audit_logs_actor_agent_run_id_agent_runs')),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_audit_logs_actor_user_id_users')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_audit_logs_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_table('reviews',
    sa.Column('artifact_version_id', sa.Uuid(), nullable=False),
    sa.Column('workflow_node_id', sa.Uuid(), nullable=False),
    sa.Column('reviewer_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'NEEDS_CHANGES', 'REJECTED', name='reviewstatus', native_enum=False, length=20), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['artifact_version_id'], ['artifact_versions.id'], name=op.f('fk_reviews_artifact_version_id_artifact_versions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], name=op.f('fk_reviews_reviewer_id_users')),
    sa.ForeignKeyConstraint(['workflow_node_id'], ['workflow_nodes.id'], name=op.f('fk_reviews_workflow_node_id_workflow_nodes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reviews'))
    )
    op.create_table('review_comments',
    sa.Column('review_id', sa.Uuid(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_review_comments_author_id_users')),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], name=op.f('fk_review_comments_review_id_reviews'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_comments'))
    )
    # Deferred FK for artifacts <-> artifact_versions circular reference —
    # see the comment on the 'artifacts' table above. batch_alter_table
    # keeps this portable: a plain ALTER TABLE on Postgres, and SQLite's
    # required copy-and-move on SQLite (which has no ALTER ADD CONSTRAINT).
    with op.batch_alter_table('artifacts') as batch_op:
        batch_op.create_foreign_key(
            op.f('fk_artifacts_current_version_id'),
            'artifact_versions',
            ['current_version_id'], ['id'],
            ondelete='SET NULL',
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the deferred FK first so neither 'artifacts' nor
    # 'artifact_versions' has a dependent constraint blocking its drop.
    with op.batch_alter_table('artifacts') as batch_op:
        batch_op.drop_constraint(op.f('fk_artifacts_current_version_id'), type_='foreignkey')
    op.drop_table('review_comments')
    op.drop_table('reviews')
    op.drop_table('audit_logs')
    op.drop_table('artifact_versions')
    op.drop_table('workflow_edges')
    op.drop_table('artifacts')
    op.drop_table('agent_runs')
    op.drop_table('workflow_nodes')
    op.drop_table('project_members')
    op.drop_table('projects')
    op.drop_table('agent_prompts')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('agent_definitions')
    # ### end Alembic commands ###
