"""project engineering setup

Revision ID: 36d5f7616d86
Revises: 7a2d9c4e1f38
Create Date: 2026-09-08 02:42:43.941289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36d5f7616d86'
down_revision: Union[str, None] = '7a2d9c4e1f38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_engineering_setups',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('application_type', sa.String(length=100), nullable=False),
    sa.Column('primary_language', sa.String(length=100), nullable=False),
    sa.Column('frontend_framework', sa.String(length=100), nullable=True),
    sa.Column('backend_framework', sa.String(length=100), nullable=True),
    sa.Column('database', sa.String(length=100), nullable=True),
    sa.Column('cloud_provider', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_project_engineering_setups_created_by_id_users')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_engineering_setups_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_engineering_setups')),
    sa.UniqueConstraint('project_id', name=op.f('uq_project_engineering_setups_project_id'))
    )
    op.create_table('project_coding_standards',
    sa.Column('setup_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['setup_id'], ['project_engineering_setups.id'], name=op.f('fk_project_coding_standards_setup_id_project_engineering_setups'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_coding_standards'))
    )
    op.create_table('project_command_configs',
    sa.Column('setup_id', sa.Uuid(), nullable=False),
    sa.Column('build_command', sa.String(length=500), nullable=True),
    sa.Column('test_commands', sa.JSON(), nullable=False),
    sa.Column('lint_command', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['setup_id'], ['project_engineering_setups.id'], name=op.f('fk_project_command_configs_setup_id_project_engineering_setups'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_command_configs')),
    sa.UniqueConstraint('setup_id', name=op.f('uq_project_command_configs_setup_id'))
    )
    op.create_table('project_documentation_configs',
    sa.Column('setup_id', sa.Uuid(), nullable=False),
    sa.Column('target', sa.Enum('INTERNAL_ONLY', 'CONFLUENCE', 'REPO_MARKDOWN', 'CONFLUENCE_AND_REPO', name='documentationtarget', native_enum=False, length=30), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['setup_id'], ['project_engineering_setups.id'], name=op.f('fk_project_documentation_configs_setup_id_project_engineering_setups'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_documentation_configs')),
    sa.UniqueConstraint('setup_id', name=op.f('uq_project_documentation_configs_setup_id'))
    )
    op.create_table('project_guardrails',
    sa.Column('setup_id', sa.Uuid(), nullable=False),
    sa.Column('rule_text', sa.Text(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['setup_id'], ['project_engineering_setups.id'], name=op.f('fk_project_guardrails_setup_id_project_engineering_setups'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_guardrails'))
    )
    op.create_table('project_jira_configs',
    sa.Column('setup_id', sa.Uuid(), nullable=False),
    sa.Column('option', sa.Enum('CONNECT_EXISTING_PROJECT', 'MAPPING_ONLY', 'SKIP_FOR_NOW', name='jirasetupoption', native_enum=False, length=30), nullable=False),
    sa.Column('jira_project_link_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['jira_project_link_id'], ['jira_project_links.id'], name=op.f('fk_project_jira_configs_jira_project_link_id_jira_project_links'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['setup_id'], ['project_engineering_setups.id'], name=op.f('fk_project_jira_configs_setup_id_project_engineering_setups'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_jira_configs')),
    sa.UniqueConstraint('setup_id', name=op.f('uq_project_jira_configs_setup_id'))
    )
    op.create_table('project_repository_configs',
    sa.Column('setup_id', sa.Uuid(), nullable=False),
    sa.Column('option', sa.Enum('CONNECT_EXISTING_REPO', 'CREATE_NEW_REPO', 'SKIP_FOR_NOW', name='githubsetupoption', native_enum=False, length=30), nullable=False),
    sa.Column('repository_id', sa.Uuid(), nullable=True),
    sa.Column('new_repo_name', sa.String(length=255), nullable=True),
    sa.Column('branch_naming_pattern', sa.String(length=255), nullable=False),
    sa.Column('target_branch', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], name=op.f('fk_project_repository_configs_repository_id_repositories'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['setup_id'], ['project_engineering_setups.id'], name=op.f('fk_project_repository_configs_setup_id_project_engineering_setups'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_repository_configs')),
    sa.UniqueConstraint('setup_id', name=op.f('uq_project_repository_configs_setup_id'))
    )
    # NOTE: alembic --autogenerate also detected two unrelated missing FKs
    # (stories.source_artifact_version_id, story_delivery_lanes.current_node_id)
    # — pre-existing drift between the ORM models and this DB, not
    # anything this migration's own feature touches. Deliberately left out
    # of this migration to keep it scoped to Project Engineering Setup
    # only; that drift should be its own separate migration if/when
    # addressed.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_repository_configs')
    op.drop_table('project_jira_configs')
    op.drop_table('project_guardrails')
    op.drop_table('project_documentation_configs')
    op.drop_table('project_command_configs')
    op.drop_table('project_coding_standards')
    op.drop_table('project_engineering_setups')
    # ### end Alembic commands ###
