"""story level implementation

Revision ID: 37a3a4f55640
Revises: 115697daea96
Create Date: 2026-09-02 09:32:10.215621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37a3a4f55640'
down_revision: Union[str, None] = '115697daea96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('implementation_runs', sa.Column('story_id', sa.Uuid(), nullable=True))
    op.add_column('implementation_runs', sa.Column('lane_id', sa.Uuid(), nullable=True))
    op.add_column('implementation_runs', sa.Column('story_lld_artifact_id', sa.Uuid(), nullable=True))
    op.add_column('implementation_runs', sa.Column('assigned_user_id', sa.Uuid(), nullable=True))
    op.add_column('implementation_runs', sa.Column('assigned_agent_key', sa.String(length=100), nullable=True))
    # NOTE: server_default added by hand — `implementation_runs` already
    # has rows.
    op.add_column('implementation_runs', sa.Column('pr_description', sa.Text(), nullable=False, server_default=''))
    op.alter_column('implementation_runs', 'pr_description', server_default=None)
    op.create_foreign_key(op.f('fk_implementation_runs_lane_id_story_delivery_lanes'), 'implementation_runs', 'story_delivery_lanes', ['lane_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_implementation_runs_story_id_stories'), 'implementation_runs', 'stories', ['story_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_implementation_runs_assigned_user_id_users'), 'implementation_runs', 'users', ['assigned_user_id'], ['id'])
    op.create_foreign_key(op.f('fk_implementation_runs_story_lld_artifact_id_story_artifacts'), 'implementation_runs', 'story_artifacts', ['story_lld_artifact_id'], ['id'], ondelete='SET NULL')
    # NOTE: autogenerate also proposed re-creating
    # 'fk_stories_source_artifact_version_id' and
    # 'fk_story_delivery_lanes_current_node_id' here — the same known
    # false-positive with use_alter=True FKs seen in earlier migrations
    # this session; both constraints already exist, so both are dropped
    # from this migration.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_implementation_runs_story_lld_artifact_id_story_artifacts'), 'implementation_runs', type_='foreignkey')
    op.drop_constraint(op.f('fk_implementation_runs_assigned_user_id_users'), 'implementation_runs', type_='foreignkey')
    op.drop_constraint(op.f('fk_implementation_runs_story_id_stories'), 'implementation_runs', type_='foreignkey')
    op.drop_constraint(op.f('fk_implementation_runs_lane_id_story_delivery_lanes'), 'implementation_runs', type_='foreignkey')
    op.drop_column('implementation_runs', 'pr_description')
    op.drop_column('implementation_runs', 'assigned_agent_key')
    op.drop_column('implementation_runs', 'assigned_user_id')
    op.drop_column('implementation_runs', 'story_lld_artifact_id')
    op.drop_column('implementation_runs', 'lane_id')
    op.drop_column('implementation_runs', 'story_id')
    # ### end Alembic commands ###
