"""github integration foundation

Revision ID: 4bbbadb6fb67
Revises: d515b8308e18
Create Date: 2026-08-31 10:23:19.033534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bbbadb6fb67'
down_revision: Union[str, None] = 'd515b8308e18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('integration_connections',
    sa.Column('integration_id', sa.Uuid(), nullable=False),
    sa.Column('access_token_encrypted', sa.Text(), nullable=False),
    sa.Column('token_last_four', sa.String(length=4), nullable=False),
    sa.Column('github_username', sa.String(length=255), nullable=True),
    sa.Column('scopes', sa.JSON(), nullable=True),
    sa.Column('connected_by_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('NOT_CONNECTED', 'CONNECTED', 'ERROR', name='integrationstatus', native_enum=False, length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['connected_by_id'], ['users.id'], name=op.f('fk_integration_connections_connected_by_id_users')),
    sa.ForeignKeyConstraint(['integration_id'], ['integrations.id'], name=op.f('fk_integration_connections_integration_id_integrations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_integration_connections'))
    )
    op.create_table('repositories',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('connection_id', sa.Uuid(), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('default_branch', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('html_url', sa.String(length=500), nullable=True),
    sa.Column('is_private', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['integration_connections.id'], name=op.f('fk_repositories_connection_id_integration_connections')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_repositories_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_repositories'))
    )
    op.create_table('repository_snapshots',
    sa.Column('repository_id', sa.Uuid(), nullable=False),
    sa.Column('ref', sa.String(length=255), nullable=False),
    sa.Column('commit_sha', sa.String(length=64), nullable=False),
    sa.Column('file_count', sa.Integer(), nullable=False),
    sa.Column('truncated', sa.Boolean(), nullable=False),
    sa.Column('triggered_by_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], name=op.f('fk_repository_snapshots_repository_id_repositories'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['triggered_by_id'], ['users.id'], name=op.f('fk_repository_snapshots_triggered_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_repository_snapshots'))
    )
    op.create_table('repository_file_index',
    sa.Column('snapshot_id', sa.Uuid(), nullable=False),
    sa.Column('path', sa.String(length=1000), nullable=False),
    sa.Column('entry_type', sa.Enum('FILE', 'DIRECTORY', name='repositoryfileentrytype', native_enum=False, length=10), nullable=False),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('sha', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['repository_snapshots.id'], name=op.f('fk_repository_file_index_snapshot_id_repository_snapshots'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_repository_file_index'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('repository_file_index')
    op.drop_table('repository_snapshots')
    op.drop_table('repositories')
    op.drop_table('integration_connections')
    # ### end Alembic commands ###
