"""story level testing

Revision ID: 521b141a78b7
Revises: f85a6e6ff762
Create Date: 2026-09-02 10:31:46.971617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '521b141a78b7'
down_revision: Union[str, None] = 'f85a6e6ff762'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: autogenerate also proposed re-creating
    # 'fk_stories_source_artifact_version_id' and
    # 'fk_story_delivery_lanes_current_node_id' here — the same known
    # false-positive with use_alter=True FKs seen in earlier migrations
    # this session; both constraints already exist, so both are omitted.
    op.add_column('test_runs', sa.Column('lane_id', sa.Uuid(), nullable=True))
    op.add_column('test_runs', sa.Column('story_artifact_id', sa.Uuid(), nullable=True))
    op.add_column('test_runs', sa.Column('test_agent_key', sa.String(length=100), nullable=True))
    # NOTE: server_default added by hand — `test_runs` already has rows.
    op.add_column('test_runs', sa.Column('evidence_attachments', sa.JSON(), nullable=False, server_default='[]'))
    op.alter_column('test_runs', 'evidence_attachments', server_default=None)
    op.alter_column('test_runs', 'workflow_node_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_foreign_key(op.f('fk_test_runs_story_artifact_id_story_artifacts'), 'test_runs', 'story_artifacts', ['story_artifact_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_test_runs_lane_id_story_delivery_lanes'), 'test_runs', 'story_delivery_lanes', ['lane_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_test_runs_lane_id_story_delivery_lanes'), 'test_runs', type_='foreignkey')
    op.drop_constraint(op.f('fk_test_runs_story_artifact_id_story_artifacts'), 'test_runs', type_='foreignkey')
    op.alter_column('test_runs', 'workflow_node_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('test_runs', 'evidence_attachments')
    op.drop_column('test_runs', 'test_agent_key')
    op.drop_column('test_runs', 'story_artifact_id')
    op.drop_column('test_runs', 'lane_id')
    # ### end Alembic commands ###
