"""knowledge base and RAG retrieval improvements

Revision ID: 6faec25eb1b1
Revises: ab374595c693
Create Date: 2026-08-30 22:08:20.961728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6faec25eb1b1'
down_revision: Union[str, None] = 'ab374595c693'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_chunks', sa.Column('stage', sa.String(length=100), nullable=True))
    op.add_column('knowledge_chunks', sa.Column('domain', sa.String(length=100), nullable=True))
    op.add_column('knowledge_chunks', sa.Column('project_type', sa.String(length=100), nullable=True))

    # content_type/tags/rag_top_k/max_rag_tokens are NOT NULL on tables
    # that already have rows — server_default added by hand (autogenerate
    # didn't include one) to backfill them, same pattern as every earlier
    # migration in this project. Matches each column's own ORM default;
    # dropped after backfilling so future inserts rely on that default
    # instead of a DB-level one staying around forever.
    op.add_column(
        'knowledge_chunks',
        sa.Column(
            'content_type',
            sa.Enum('COMPANY_STANDARD', 'PAST_ARTIFACT', 'UI_GUIDELINE', 'ARCHITECTURE_RULE', 'TESTING_STANDARD', 'OTHER', name='knowledgecontenttype', native_enum=False, length=30),
            nullable=False,
            server_default='OTHER',
        ),
    )
    op.alter_column('knowledge_chunks', 'content_type', server_default=None)
    op.add_column('knowledge_chunks', sa.Column('tags', sa.JSON(), nullable=False, server_default='[]'))
    op.alter_column('knowledge_chunks', 'tags', server_default=None)

    op.add_column('workflow_nodes', sa.Column('rag_top_k', sa.Integer(), nullable=False, server_default='5'))
    op.alter_column('workflow_nodes', 'rag_top_k', server_default=None)
    op.add_column('workflow_nodes', sa.Column('max_rag_tokens', sa.Integer(), nullable=False, server_default='2000'))
    op.alter_column('workflow_nodes', 'max_rag_tokens', server_default=None)
    # ### end Alembic commands ###

    # workflows/sdlc-workflow.json overrides these stages' RAG budgets to
    # lean harder on retrieved knowledge (see workflow_templates.py) —
    # apply the same overrides to existing projects' rows too.
    op.execute("UPDATE workflow_nodes SET rag_top_k = 8, max_rag_tokens = 3000 WHERE node_key = 'hld'")
    op.execute("UPDATE workflow_nodes SET rag_top_k = 6, max_rag_tokens = 2500 WHERE node_key = 'story_crafting'")
    op.execute("UPDATE workflow_nodes SET rag_top_k = 8, max_rag_tokens = 4000 WHERE node_key = 'implementation'")
    op.execute("UPDATE workflow_nodes SET rag_top_k = 6, max_rag_tokens = 3000 WHERE node_key = 'testing'")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow_nodes', 'max_rag_tokens')
    op.drop_column('workflow_nodes', 'rag_top_k')
    op.drop_column('knowledge_chunks', 'tags')
    op.drop_column('knowledge_chunks', 'content_type')
    op.drop_column('knowledge_chunks', 'project_type')
    op.drop_column('knowledge_chunks', 'domain')
    op.drop_column('knowledge_chunks', 'stage')
    # ### end Alembic commands ###
