"""loop engine state and events

Revision ID: 6fda3e686ac4
Revises: e477e224c4c6
Create Date: 2026-08-30 20:36:17.944942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fda3e686ac4'
down_revision: Union[str, None] = 'e477e224c4c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_run_loop_events',
    sa.Column('agent_run_id', sa.Uuid(), nullable=False),
    sa.Column('iteration', sa.Integer(), nullable=False),
    sa.Column('step', sa.Enum('PLAN', 'RETRIEVE_CONTEXT', 'GENERATE_DRAFT', 'VALIDATE', 'IMPROVE', 'READY_FOR_REVIEW', name='loopsteptype', native_enum=False, length=20), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('validation_issues', sa.JSON(), nullable=True),
    sa.Column('content_snapshot', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], name=op.f('fk_agent_run_loop_events_agent_run_id_agent_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_run_loop_events'))
    )
    # loop_status/loop_iteration are NOT NULL on a table that already has
    # rows — server_default added by hand (autogenerate didn't include one,
    # same as the earlier User.role migration) to backfill them, then
    # dropped so future inserts rely on the ORM default instead of a
    # DB-level one staying around forever.
    op.add_column('agent_runs', sa.Column('loop_status', sa.Enum('NOT_STARTED', 'RUNNING', 'COMPLETED_QUALITY_MET', 'COMPLETED_MAX_ITERATIONS', 'COMPLETED_NO_CRITICAL_ISSUES', 'WAITING_FOR_CLARIFICATION', 'FAILED', name='loopstatus', native_enum=False, length=30), nullable=False, server_default='NOT_STARTED'))
    op.alter_column('agent_runs', 'loop_status', server_default=None)
    op.add_column('agent_runs', sa.Column('loop_current_step', sa.Enum('PLAN', 'RETRIEVE_CONTEXT', 'GENERATE_DRAFT', 'VALIDATE', 'IMPROVE', 'READY_FOR_REVIEW', name='loopsteptype', native_enum=False, length=20), nullable=True))
    op.add_column('agent_runs', sa.Column('loop_iteration', sa.Integer(), nullable=False, server_default='0'))
    op.alter_column('agent_runs', 'loop_iteration', server_default=None)
    op.add_column('agent_runs', sa.Column('loop_max_iterations', sa.Integer(), nullable=True))
    op.add_column('agent_runs', sa.Column('loop_quality_threshold', sa.Float(), nullable=True))
    op.add_column('agent_runs', sa.Column('loop_quality_score', sa.Float(), nullable=True))
    op.add_column('agent_runs', sa.Column('loop_validation_issues', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_runs', 'loop_validation_issues')
    op.drop_column('agent_runs', 'loop_quality_score')
    op.drop_column('agent_runs', 'loop_quality_threshold')
    op.drop_column('agent_runs', 'loop_max_iterations')
    op.drop_column('agent_runs', 'loop_iteration')
    op.drop_column('agent_runs', 'loop_current_step')
    op.drop_column('agent_runs', 'loop_status')
    op.drop_table('agent_run_loop_events')
    # ### end Alembic commands ###
