"""scrum story lanes

Revision ID: 8b2b6dcf48ad
Revises: e1fb7ab8d6ab
Create Date: 2026-09-01 23:10:44.998208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b2b6dcf48ad'
down_revision: Union[str, None] = 'e1fb7ab8d6ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sprints',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('PLANNING', 'ACTIVE', 'COMPLETED', name='sprintstatus', native_enum=False, length=20), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_sprints_created_by_id_users')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_sprints_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sprints'))
    )
    op.create_table('stories',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('source_artifact_version_id', sa.Uuid(), nullable=False),
    sa.Column('story_type', sa.Enum('VERTICAL', 'HORIZONTAL', name='storytype', native_enum=False, length=20), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_SPRINT', 'LANE_ACTIVE', 'DONE', name='storystatus', native_enum=False, length=20), nullable=False),
    sa.Column('epic', sa.String(length=255), nullable=False),
    sa.Column('feature', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('user_story', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=50), nullable=False),
    sa.Column('dependencies', sa.Text(), nullable=False),
    sa.Column('acceptance_criteria', sa.JSON(), nullable=False),
    sa.Column('definition_of_done', sa.JSON(), nullable=False),
    sa.Column('owner_user_id', sa.Uuid(), nullable=True),
    sa.Column('sprint_id', sa.Uuid(), nullable=True),
    sa.Column('lane_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_stories_created_by_id_users')),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], name=op.f('fk_stories_owner_user_id_users')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_stories_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_artifact_version_id'], ['artifact_versions.id'], name='fk_stories_source_artifact_version_id', ondelete='CASCADE', use_alter=True),
    sa.ForeignKeyConstraint(['sprint_id'], ['sprints.id'], name=op.f('fk_stories_sprint_id_sprints'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stories')),
    sa.UniqueConstraint('project_id', 'title', name=op.f('uq_stories_project_id_title'))
    )
    op.add_column('artifacts', sa.Column('story_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(op.f('fk_artifacts_story_id_stories'), 'artifacts', 'stories', ['story_id'], ['id'], ondelete='CASCADE')
    op.add_column('implementation_tasks', sa.Column('story_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(op.f('fk_implementation_tasks_story_id_stories'), 'implementation_tasks', 'stories', ['story_id'], ['id'], ondelete='CASCADE')
    op.add_column('pr_review_runs', sa.Column('story_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(op.f('fk_pr_review_runs_story_id_stories'), 'pr_review_runs', 'stories', ['story_id'], ['id'], ondelete='CASCADE')
    op.add_column('pull_request_links', sa.Column('story_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(op.f('fk_pull_request_links_story_id_stories'), 'pull_request_links', 'stories', ['story_id'], ['id'], ondelete='CASCADE')
    op.add_column('test_runs', sa.Column('story_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(op.f('fk_test_runs_story_id_stories'), 'test_runs', 'stories', ['story_id'], ['id'], ondelete='CASCADE')
    op.add_column('workflow_edges', sa.Column('story_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(op.f('fk_workflow_edges_story_id_stories'), 'workflow_edges', 'stories', ['story_id'], ['id'], ondelete='CASCADE')
    op.add_column('workflow_nodes', sa.Column('story_id', sa.Uuid(), nullable=True))
    op.drop_constraint('uq_workflow_nodes_project_id_node_key', 'workflow_nodes', type_='unique')
    op.create_unique_constraint(op.f('uq_workflow_nodes_project_id_node_key_story_id'), 'workflow_nodes', ['project_id', 'node_key', 'story_id'])
    op.create_foreign_key(op.f('fk_workflow_nodes_story_id_stories'), 'workflow_nodes', 'stories', ['story_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_workflow_nodes_story_id_stories'), 'workflow_nodes', type_='foreignkey')
    op.drop_constraint(op.f('uq_workflow_nodes_project_id_node_key_story_id'), 'workflow_nodes', type_='unique')
    op.create_unique_constraint('uq_workflow_nodes_project_id_node_key', 'workflow_nodes', ['project_id', 'node_key'])
    op.drop_column('workflow_nodes', 'story_id')
    op.drop_constraint(op.f('fk_workflow_edges_story_id_stories'), 'workflow_edges', type_='foreignkey')
    op.drop_column('workflow_edges', 'story_id')
    op.drop_constraint(op.f('fk_test_runs_story_id_stories'), 'test_runs', type_='foreignkey')
    op.drop_column('test_runs', 'story_id')
    op.drop_constraint(op.f('fk_pull_request_links_story_id_stories'), 'pull_request_links', type_='foreignkey')
    op.drop_column('pull_request_links', 'story_id')
    op.drop_constraint(op.f('fk_pr_review_runs_story_id_stories'), 'pr_review_runs', type_='foreignkey')
    op.drop_column('pr_review_runs', 'story_id')
    op.drop_constraint(op.f('fk_implementation_tasks_story_id_stories'), 'implementation_tasks', type_='foreignkey')
    op.drop_column('implementation_tasks', 'story_id')
    op.drop_constraint(op.f('fk_artifacts_story_id_stories'), 'artifacts', type_='foreignkey')
    op.drop_column('artifacts', 'story_id')
    op.drop_table('stories')
    op.drop_table('sprints')
    # ### end Alembic commands ###
