"""workflow node required evidence section

Revision ID: a1c2e5f7d9b3
Revises: be4954667239
Create Date: 2026-08-31 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1c2e5f7d9b3'
down_revision: Union[str, None] = 'be4954667239'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow_nodes', sa.Column('required_evidence_section', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow_nodes', 'required_evidence_section')
    # ### end Alembic commands ###
