"""confluence integration

Revision ID: a860fd34fd83
Revises: 0f1ce2a8f5d0
Create Date: 2026-09-01 10:59:21.185263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a860fd34fd83'
down_revision: Union[str, None] = '0f1ce2a8f5d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('confluence_space_links',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('connection_id', sa.Uuid(), nullable=False),
    sa.Column('space_key', sa.String(length=50), nullable=False),
    sa.Column('space_name', sa.String(length=255), nullable=True),
    sa.Column('root_page_id', sa.String(length=100), nullable=False),
    sa.Column('root_page_url', sa.String(length=500), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['integration_connections.id'], name=op.f('fk_confluence_space_links_connection_id_integration_connections')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_confluence_space_links_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_confluence_space_links')),
    sa.UniqueConstraint('project_id', name=op.f('uq_confluence_space_links_project_id'))
    )
    op.create_table('confluence_page_links',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('confluence_space_link_id', sa.Uuid(), nullable=False),
    sa.Column('artifact_type', sa.String(length=100), nullable=False),
    sa.Column('artifact_id', sa.Uuid(), nullable=False),
    sa.Column('artifact_version_id', sa.Uuid(), nullable=False),
    sa.Column('confluence_page_id', sa.String(length=100), nullable=False),
    sa.Column('confluence_page_url', sa.String(length=500), nullable=False),
    sa.Column('confluence_page_title', sa.String(length=255), nullable=False),
    sa.Column('confluence_page_version', sa.Integer(), nullable=False),
    sa.Column('triggered_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.id'], name=op.f('fk_confluence_page_links_artifact_id_artifacts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['artifact_version_id'], ['artifact_versions.id'], name=op.f('fk_confluence_page_links_artifact_version_id_artifact_versions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['confluence_space_link_id'], ['confluence_space_links.id'], name=op.f('fk_confluence_page_links_confluence_space_link_id_confluence_space_links'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_confluence_page_links_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['triggered_by_user_id'], ['users.id'], name=op.f('fk_confluence_page_links_triggered_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_confluence_page_links')),
    sa.UniqueConstraint('confluence_space_link_id', 'artifact_type', name=op.f('uq_confluence_page_links_confluence_space_link_id_artifact_type'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('confluence_page_links')
    op.drop_table('confluence_space_links')
    # ### end Alembic commands ###
