"""validator agent architecture

Revision ID: ab374595c693
Revises: c1601dfd26c9
Create Date: 2026-08-30 21:40:25.859897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab374595c693'
down_revision: Union[str, None] = 'c1601dfd26c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('validator_definitions',
    sa.Column('validator_key', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('stage', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('quality_threshold', sa.Float(), nullable=False),
    sa.Column('criteria', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_validator_definitions')),
    sa.UniqueConstraint('stage', name=op.f('uq_validator_definitions_stage')),
    sa.UniqueConstraint('validator_key', name=op.f('uq_validator_definitions_validator_key'))
    )
    op.add_column('agent_run_loop_events', sa.Column('validation_result', sa.JSON(), nullable=True))
    op.add_column('agent_runs', sa.Column('loop_validation_result', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_runs', 'loop_validation_result')
    op.drop_column('agent_run_loop_events', 'validation_result')
    op.drop_table('validator_definitions')
    # ### end Alembic commands ###
