"""story points and suggested owner role

Revision ID: b31be06bf2cc
Revises: 8b2b6dcf48ad
Create Date: 2026-09-01 23:48:16.380085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b31be06bf2cc'
down_revision: Union[str, None] = '8b2b6dcf48ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: autogenerate also proposed re-creating
    # 'fk_stories_source_artifact_version_id' here — a known false-positive
    # with use_alter=True FKs (see app/models/story.py's own comment on
    # this FK); that constraint already exists from 8b2b6dcf48ad's
    # CREATE TABLE, so re-adding it would fail with a duplicate-constraint
    # error. Deliberately dropped from this migration.
    op.add_column('stories', sa.Column('suggested_owner_role', sa.String(length=50), nullable=True))
    op.add_column('stories', sa.Column('story_points', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stories', 'story_points')
    op.drop_column('stories', 'suggested_owner_role')
    # ### end Alembic commands ###
