"""add integrations model

Revision ID: b484b02df611
Revises: 7796bda4707f
Create Date: 2026-08-30 10:45:48.368303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b484b02df611'
down_revision: Union[str, None] = '7796bda4707f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('integrations',
    sa.Column('integration_name', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.Enum('JIRA', 'CONFLUENCE', 'GITHUB', 'SLACK', 'TEAMS', 'AZURE_DEVOPS', name='integrationprovider', native_enum=False, length=30), nullable=False),
    sa.Column('status', sa.Enum('NOT_CONNECTED', 'CONNECTED', 'ERROR', name='integrationstatus', native_enum=False, length=20), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=True),
    sa.Column('connected_by_id', sa.Uuid(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['connected_by_id'], ['users.id'], name=op.f('fk_integrations_connected_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_integrations'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('integrations')
    # ### end Alembic commands ###
