"""story crafting vertical horizontal fields

Revision ID: be5a5f8a64f0
Revises: b31be06bf2cc
Create Date: 2026-09-02 00:01:24.477205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be5a5f8a64f0'
down_revision: Union[str, None] = 'b31be06bf2cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: server_default added by hand on every NOT NULL column below —
    # the `stories` table already has rows (real synced stories from
    # earlier testing), and a bare ADD COLUMN ... NOT NULL with no default
    # fails against existing rows in Postgres. Dropped afterward so the
    # Python-side default (see app/models/story.py) governs new rows going
    # forward, not a stale DB-level default.
    op.add_column('stories', sa.Column('business_value', sa.Text(), nullable=False, server_default=''))
    op.add_column('stories', sa.Column('technical_areas', sa.JSON(), nullable=False, server_default='[]'))
    op.add_column('stories', sa.Column('jira_issue_type', sa.String(length=50), nullable=False, server_default=''))
    op.add_column('stories', sa.Column('suggested_subtasks', sa.JSON(), nullable=False, server_default='[]'))
    op.add_column('stories', sa.Column('release_readiness_criteria', sa.JSON(), nullable=False, server_default='[]'))
    op.alter_column('stories', 'business_value', server_default=None)
    op.alter_column('stories', 'technical_areas', server_default=None)
    op.alter_column('stories', 'jira_issue_type', server_default=None)
    op.alter_column('stories', 'suggested_subtasks', server_default=None)
    op.alter_column('stories', 'release_readiness_criteria', server_default=None)
    # NOTE: autogenerate also proposed re-creating
    # 'fk_stories_source_artifact_version_id' here — the same known
    # false-positive with use_alter=True FKs already seen in
    # b31be06bf2cc; that constraint already exists, so it's dropped from
    # this migration.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_stories_source_artifact_version_id', 'stories', type_='foreignkey')
    op.drop_column('stories', 'release_readiness_criteria')
    op.drop_column('stories', 'suggested_subtasks')
    op.drop_column('stories', 'jira_issue_type')
    op.drop_column('stories', 'technical_areas')
    op.drop_column('stories', 'business_value')
    # ### end Alembic commands ###
