"""artifact compression summaries

Revision ID: c1601dfd26c9
Revises: caaa4dc39ae8
Create Date: 2026-08-30 21:18:32.783119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1601dfd26c9'
down_revision: Union[str, None] = 'caaa4dc39ae8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artifact_versions', sa.Column('executive_summary', sa.Text(), nullable=True))
    op.add_column('artifact_versions', sa.Column('agent_context_summary', sa.Text(), nullable=True))
    op.add_column('artifact_versions', sa.Column('key_decisions', sa.JSON(), nullable=True))
    op.add_column('artifact_versions', sa.Column('open_questions', sa.JSON(), nullable=True))
    op.add_column('artifact_versions', sa.Column('risks', sa.JSON(), nullable=True))
    op.add_column('artifact_versions', sa.Column('generated_summary_at', sa.DateTime(timezone=True), nullable=True))

    # workflow_nodes already has rows; this one is NOT NULL, so it needs a
    # server_default to backfill them — same pattern as the earlier
    # User.role, graph-engine, and token-budget migrations. Matches
    # WorkflowNode's own column default (empty list); dropped after
    # backfilling so future inserts rely on the ORM default instead of a
    # DB-level one staying around forever.
    op.add_column(
        'workflow_nodes', sa.Column('full_content_artifact_types', sa.JSON(), nullable=False, server_default='[]')
    )
    op.alter_column('workflow_nodes', 'full_content_artifact_types', server_default=None)
    # ### end Alembic commands ###

    # workflows/sdlc-workflow.json overrides these two stages to directly
    # depend on an upstream artifact's detailed content (see
    # workflow_templates.py) — apply that same override to existing
    # projects' rows too, so they match what a newly-created project gets
    # from the template.
    op.execute("UPDATE workflow_nodes SET full_content_artifact_types = '[\"lld_document\"]' WHERE node_key = 'implementation'")
    op.execute("UPDATE workflow_nodes SET full_content_artifact_types = '[\"code_change\"]' WHERE node_key = 'testing'")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow_nodes', 'full_content_artifact_types')
    op.drop_column('artifact_versions', 'generated_summary_at')
    op.drop_column('artifact_versions', 'risks')
    op.drop_column('artifact_versions', 'open_questions')
    op.drop_column('artifact_versions', 'key_decisions')
    op.drop_column('artifact_versions', 'agent_context_summary')
    op.drop_column('artifact_versions', 'executive_summary')
    # ### end Alembic commands ###
