"""add user role for permissions

Revision ID: c76ec5e8fb65
Revises: b484b02df611
Create Date: 2026-08-30 15:17:52.290387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c76ec5e8fb65'
down_revision: Union[str, None] = 'b484b02df611'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # server_default added by hand (autogenerate didn't include one) — this
    # table already has rows, and a NOT NULL column needs a default to
    # backfill them. Matches the model's Python-side default (VIEWER); the
    # server_default is dropped after backfilling so future inserts rely
    # on the ORM default instead of a DB-level one staying around forever.
    op.add_column(
        'users',
        sa.Column(
            'role',
            sa.Enum('ADMIN', 'BA', 'PRODUCT_OWNER', 'ARCHITECT', 'TECH_LEAD', 'DEVELOPER', 'QA', 'DEVOPS', 'VIEWER', name='userrole', native_enum=False, length=20),
            nullable=False,
            server_default='VIEWER',
        ),
    )
    op.alter_column('users', 'role', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
