"""token budget management

Revision ID: caaa4dc39ae8
Revises: 6fda3e686ac4
Create Date: 2026-08-30 20:59:03.199369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'caaa4dc39ae8'
down_revision: Union[str, None] = '6fda3e686ac4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_runs', sa.Column('context_token_budget', sa.Integer(), nullable=True))
    op.add_column('agent_runs', sa.Column('output_token_budget', sa.Integer(), nullable=True))
    op.add_column('agent_runs', sa.Column('estimated_context_tokens', sa.Integer(), nullable=True))
    op.add_column('agent_runs', sa.Column('token_budget_report', sa.JSON(), nullable=True))

    # workflow_nodes already has rows; these two are NOT NULL, so they need
    # a server_default to backfill existing rows — same pattern as the
    # earlier User.role and graph-engine migrations. Matches WorkflowNode's
    # own column defaults (see app/models/workflow.py); dropped after
    # backfilling so future inserts rely on the ORM default instead of a
    # DB-level one staying around forever.
    op.add_column('workflow_nodes', sa.Column('context_token_budget', sa.Integer(), nullable=False, server_default='8000'))
    op.alter_column('workflow_nodes', 'context_token_budget', server_default=None)
    op.add_column('workflow_nodes', sa.Column('output_token_budget', sa.Integer(), nullable=False, server_default='2048'))
    op.alter_column('workflow_nodes', 'output_token_budget', server_default=None)
    # ### end Alembic commands ###

    # The backfill above gives every existing row the generic default, but
    # workflows/sdlc-workflow.json overrides lld/implementation to larger
    # budgets (see workflow_templates.py) — apply that same override to
    # existing projects' rows too, so they match what a newly-created
    # project gets from the template.
    op.execute("UPDATE workflow_nodes SET context_token_budget = 12000, output_token_budget = 3072 WHERE node_key = 'lld'")
    op.execute(
        "UPDATE workflow_nodes SET context_token_budget = 16000, output_token_budget = 4096 "
        "WHERE node_key = 'implementation'"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow_nodes', 'output_token_budget')
    op.drop_column('workflow_nodes', 'context_token_budget')
    op.drop_column('agent_runs', 'token_budget_report')
    op.drop_column('agent_runs', 'estimated_context_tokens')
    op.drop_column('agent_runs', 'output_token_budget')
    op.drop_column('agent_runs', 'context_token_budget')
    # ### end Alembic commands ###
