"""implementation task planner

Revision ID: d515b8308e18
Revises: a1c2e5f7d9b3
Create Date: 2026-08-31 04:02:45.589268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd515b8308e18'
down_revision: Union[str, None] = 'a1c2e5f7d9b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('implementation_tasks',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('workflow_node_id', sa.Uuid(), nullable=False),
    sa.Column('artifact_id', sa.Uuid(), nullable=False),
    sa.Column('artifact_version_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('linked_story', sa.String(length=255), nullable=True),
    sa.Column('linked_lld_section', sa.String(length=255), nullable=True),
    sa.Column('area', sa.Enum('BACKEND', 'FRONTEND', 'DATABASE', 'TESTING', 'INFRA', 'DOCS', name='implementationtaskarea', native_enum=False, length=20), nullable=False),
    sa.Column('expected_paths', sa.JSON(), nullable=False),
    sa.Column('dependencies', sa.JSON(), nullable=False),
    sa.Column('acceptance_criteria', sa.JSON(), nullable=False),
    sa.Column('test_expectation', sa.Text(), nullable=False),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='implementationtaskrisklevel', native_enum=False, length=10), nullable=False),
    sa.Column('assigned_agent_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'BLOCKED', name='implementationtaskstatus', native_enum=False, length=20), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.id'], name=op.f('fk_implementation_tasks_artifact_id_artifacts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['artifact_version_id'], ['artifact_versions.id'], name=op.f('fk_implementation_tasks_artifact_version_id_artifact_versions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_implementation_tasks_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_node_id'], ['workflow_nodes.id'], name=op.f('fk_implementation_tasks_workflow_node_id_workflow_nodes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_implementation_tasks'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('implementation_tasks')
    # ### end Alembic commands ###
