"""pull request links

Revision ID: dc71869b2411
Revises: fa85083336c2
Create Date: 2026-08-31 11:55:43.206737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc71869b2411'
down_revision: Union[str, None] = 'fa85083336c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pull_request_links',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('workflow_node_id', sa.Uuid(), nullable=False),
    sa.Column('implementation_task_id', sa.Uuid(), nullable=False),
    sa.Column('implementation_run_id', sa.Uuid(), nullable=False),
    sa.Column('repository_id', sa.Uuid(), nullable=False),
    sa.Column('branch_name', sa.String(length=255), nullable=False),
    sa.Column('base_branch', sa.String(length=255), nullable=False),
    sa.Column('pr_number', sa.Integer(), nullable=False),
    sa.Column('pr_url', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'MERGED', 'CLOSED', name='pullrequeststatus', native_enum=False, length=10), nullable=False),
    sa.Column('created_by_agent', sa.Boolean(), nullable=False),
    sa.Column('triggered_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('commit_message', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['implementation_run_id'], ['implementation_runs.id'], name=op.f('fk_pull_request_links_implementation_run_id_implementation_runs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['implementation_task_id'], ['implementation_tasks.id'], name=op.f('fk_pull_request_links_implementation_task_id_implementation_tasks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_pull_request_links_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], name=op.f('fk_pull_request_links_repository_id_repositories'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['triggered_by_user_id'], ['users.id'], name=op.f('fk_pull_request_links_triggered_by_user_id_users')),
    sa.ForeignKeyConstraint(['workflow_node_id'], ['workflow_nodes.id'], name=op.f('fk_pull_request_links_workflow_node_id_workflow_nodes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pull_request_links'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pull_request_links')
    # ### end Alembic commands ###
