"""maintenance agent

Revision ID: e1fb7ab8d6ab
Revises: a860fd34fd83
Create Date: 2026-09-01 17:42:23.871027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1fb7ab8d6ab'
down_revision: Union[str, None] = 'a860fd34fd83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maintenance_runs',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('workflow_node_id', sa.Uuid(), nullable=False),
    sa.Column('triggered_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='maintenancerunstatus', native_enum=False, length=20), nullable=False),
    sa.Column('error_logs_input', sa.Text(), nullable=True),
    sa.Column('user_feedback_input', sa.Text(), nullable=True),
    sa.Column('report_markdown', sa.Text(), nullable=True),
    sa.Column('artifact_id', sa.Uuid(), nullable=True),
    sa.Column('artifact_version_id', sa.Uuid(), nullable=True),
    sa.Column('used_mock', sa.Boolean(), nullable=False),
    sa.Column('token_usage', sa.JSON(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.id'], name=op.f('fk_maintenance_runs_artifact_id_artifacts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['artifact_version_id'], ['artifact_versions.id'], name=op.f('fk_maintenance_runs_artifact_version_id_artifact_versions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_maintenance_runs_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['triggered_by_user_id'], ['users.id'], name=op.f('fk_maintenance_runs_triggered_by_user_id_users')),
    sa.ForeignKeyConstraint(['workflow_node_id'], ['workflow_nodes.id'], name=op.f('fk_maintenance_runs_workflow_node_id_workflow_nodes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_maintenance_runs'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('maintenance_runs')
    # ### end Alembic commands ###
