"""story delivery lane tables

Revision ID: e928051fc407
Revises: be5a5f8a64f0
Create Date: 2026-09-02 00:16:19.684999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e928051fc407'
down_revision: Union[str, None] = 'be5a5f8a64f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('story_assignees',
    sa.Column('story_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('assigned_by_id', sa.Uuid(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('unassigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['users.id'], name=op.f('fk_story_assignees_assigned_by_id_users')),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], name=op.f('fk_story_assignees_story_id_stories'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_story_assignees_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_story_assignees'))
    )
    op.create_table('story_delivery_lanes',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('story_id', sa.Uuid(), nullable=False),
    sa.Column('current_node_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'BLOCKED', 'COMPLETED', name='storydeliverylanestatus', native_enum=False, length=20), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_story_delivery_lanes_created_by_id_users')),
    sa.ForeignKeyConstraint(['current_node_id'], ['story_delivery_nodes.id'], name='fk_story_delivery_lanes_current_node_id', ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_story_delivery_lanes_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], name=op.f('fk_story_delivery_lanes_story_id_stories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_story_delivery_lanes')),
    sa.UniqueConstraint('story_id', name=op.f('uq_story_delivery_lanes_story_id'))
    )
    op.create_table('story_delivery_nodes',
    sa.Column('lane_id', sa.Uuid(), nullable=False),
    sa.Column('node_key', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('LOCKED', 'READY', 'IN_PROGRESS', 'WAITING_FOR_REVIEW', 'BLOCKED', 'COMPLETED', name='storydeliverynodestatus', native_enum=False, length=20), nullable=False),
    sa.Column('assigned_role', sa.String(length=50), nullable=True),
    sa.Column('assigned_user_id', sa.Uuid(), nullable=True),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('blocked_reason', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['users.id'], name=op.f('fk_story_delivery_nodes_assigned_user_id_users')),
    sa.ForeignKeyConstraint(['lane_id'], ['story_delivery_lanes.id'], name=op.f('fk_story_delivery_nodes_lane_id_story_delivery_lanes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_story_delivery_nodes'))
    )
    op.create_table('story_activity_logs',
    sa.Column('story_id', sa.Uuid(), nullable=False),
    sa.Column('lane_id', sa.Uuid(), nullable=True),
    sa.Column('node_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_story_activity_logs_actor_user_id_users')),
    sa.ForeignKeyConstraint(['lane_id'], ['story_delivery_lanes.id'], name=op.f('fk_story_activity_logs_lane_id_story_delivery_lanes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['node_id'], ['story_delivery_nodes.id'], name=op.f('fk_story_activity_logs_node_id_story_delivery_nodes'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], name=op.f('fk_story_activity_logs_story_id_stories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_story_activity_logs'))
    )
    op.create_table('story_artifacts',
    sa.Column('story_id', sa.Uuid(), nullable=False),
    sa.Column('lane_id', sa.Uuid(), nullable=True),
    sa.Column('node_id', sa.Uuid(), nullable=True),
    sa.Column('artifact_type', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content_markdown', sa.Text(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_story_artifacts_created_by_id_users')),
    sa.ForeignKeyConstraint(['lane_id'], ['story_delivery_lanes.id'], name=op.f('fk_story_artifacts_lane_id_story_delivery_lanes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['node_id'], ['story_delivery_nodes.id'], name=op.f('fk_story_artifacts_node_id_story_delivery_nodes'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], name=op.f('fk_story_artifacts_story_id_stories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_story_artifacts'))
    )
    op.create_table('story_delivery_edges',
    sa.Column('lane_id', sa.Uuid(), nullable=False),
    sa.Column('source_node_id', sa.Uuid(), nullable=False),
    sa.Column('target_node_id', sa.Uuid(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lane_id'], ['story_delivery_lanes.id'], name=op.f('fk_story_delivery_edges_lane_id_story_delivery_lanes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_node_id'], ['story_delivery_nodes.id'], name=op.f('fk_story_delivery_edges_source_node_id_story_delivery_nodes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_node_id'], ['story_delivery_nodes.id'], name=op.f('fk_story_delivery_edges_target_node_id_story_delivery_nodes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_story_delivery_edges'))
    )
    # NOTE: server_default added by hand — `stories` already has rows, and
    # a bare ADD COLUMN ... NOT NULL with no default fails against them in
    # Postgres. Dropped right after so the Python-side default (see
    # app/models/story.py) governs new rows going forward.
    op.add_column('stories', sa.Column('description', sa.Text(), nullable=False, server_default=''))
    op.alter_column('stories', 'description', server_default=None)
    op.add_column('stories', sa.Column('jira_issue_key', sa.String(length=50), nullable=True))
    op.alter_column('stories', 'source_artifact_version_id',
               existing_type=sa.UUID(),
               nullable=True)
    # NOTE: autogenerate also proposed re-creating
    # 'fk_stories_source_artifact_version_id' here — the same known
    # false-positive with use_alter=True FKs already seen in
    # b31be06bf2cc/be5a5f8a64f0; that constraint already exists, so it's
    # dropped from this migration.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stories', 'source_artifact_version_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('stories', 'jira_issue_key')
    op.drop_column('stories', 'description')
    op.drop_table('story_delivery_edges')
    op.drop_table('story_artifacts')
    op.drop_table('story_activity_logs')
    op.drop_table('story_delivery_nodes')
    op.drop_table('story_delivery_lanes')
    op.drop_table('story_assignees')
    # ### end Alembic commands ###
