"""nullable implementation task project links

Revision ID: f85a6e6ff762
Revises: 37a3a4f55640
Create Date: 2026-09-02 09:46:55.461116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f85a6e6ff762'
down_revision: Union[str, None] = '37a3a4f55640'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('implementation_tasks', 'workflow_node_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('implementation_tasks', 'artifact_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('implementation_tasks', 'artifact_version_id',
               existing_type=sa.UUID(),
               nullable=True)
    # NOTE: autogenerate also proposed re-creating
    # 'fk_stories_source_artifact_version_id' and
    # 'fk_story_delivery_lanes_current_node_id' here — the same known
    # false-positive with use_alter=True FKs seen in earlier migrations
    # this session; both constraints already exist, so both are dropped
    # from this migration.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('implementation_tasks', 'artifact_version_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('implementation_tasks', 'artifact_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('implementation_tasks', 'workflow_node_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
