"""implementation runs

Revision ID: fa85083336c2
Revises: 4bbbadb6fb67
Create Date: 2026-08-31 11:34:36.298022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa85083336c2'
down_revision: Union[str, None] = '4bbbadb6fb67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('implementation_runs',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('implementation_task_id', sa.Uuid(), nullable=False),
    sa.Column('repository_snapshot_id', sa.Uuid(), nullable=True),
    sa.Column('triggered_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('agent_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='implementationrunstatus', native_enum=False, length=20), nullable=False),
    sa.Column('proposed_file_changes', sa.JSON(), nullable=False),
    sa.Column('diff_text', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('test_command', sa.String(length=500), nullable=False),
    sa.Column('risks', sa.JSON(), nullable=False),
    sa.Column('used_mock', sa.Boolean(), nullable=False),
    sa.Column('token_usage', sa.JSON(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_status', sa.Enum('PENDING_REVIEW', 'ACCEPTED', 'REJECTED', name='implementationrunreviewstatus', native_enum=False, length=20), nullable=False),
    sa.Column('reviewed_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_comment', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['implementation_task_id'], ['implementation_tasks.id'], name=op.f('fk_implementation_runs_implementation_task_id_implementation_tasks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_implementation_runs_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repository_snapshot_id'], ['repository_snapshots.id'], name=op.f('fk_implementation_runs_repository_snapshot_id_repository_snapshots'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], name=op.f('fk_implementation_runs_reviewed_by_user_id_users')),
    sa.ForeignKeyConstraint(['triggered_by_user_id'], ['users.id'], name=op.f('fk_implementation_runs_triggered_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_implementation_runs'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('implementation_runs')
    # ### end Alembic commands ###
