"""pr review runs

Revision ID: fb79b6f9cf31
Revises: 0820af90af5f
Create Date: 2026-08-31 12:58:11.250814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb79b6f9cf31'
down_revision: Union[str, None] = '0820af90af5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pr_review_runs',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('workflow_node_id', sa.Uuid(), nullable=False),
    sa.Column('implementation_task_id', sa.Uuid(), nullable=False),
    sa.Column('implementation_run_id', sa.Uuid(), nullable=False),
    sa.Column('pull_request_link_id', sa.Uuid(), nullable=False),
    sa.Column('triggered_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='prreviewrunstatus', native_enum=False, length=20), nullable=False),
    sa.Column('overall_recommendation', sa.Enum('APPROVE', 'REQUEST_CHANGES', 'COMMENT_ONLY', name='prreviewrecommendation', native_enum=False, length=20), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('critical_findings', sa.JSON(), nullable=False),
    sa.Column('major_findings', sa.JSON(), nullable=False),
    sa.Column('minor_findings', sa.JSON(), nullable=False),
    sa.Column('missing_tests', sa.JSON(), nullable=False),
    sa.Column('suggested_comments', sa.JSON(), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('final_reviewer_note', sa.Text(), nullable=False),
    sa.Column('posted_comments', sa.JSON(), nullable=False),
    sa.Column('used_mock', sa.Boolean(), nullable=False),
    sa.Column('token_usage', sa.JSON(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['implementation_run_id'], ['implementation_runs.id'], name=op.f('fk_pr_review_runs_implementation_run_id_implementation_runs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['implementation_task_id'], ['implementation_tasks.id'], name=op.f('fk_pr_review_runs_implementation_task_id_implementation_tasks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_pr_review_runs_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pull_request_link_id'], ['pull_request_links.id'], name=op.f('fk_pr_review_runs_pull_request_link_id_pull_request_links'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['triggered_by_user_id'], ['users.id'], name=op.f('fk_pr_review_runs_triggered_by_user_id_users')),
    sa.ForeignKeyConstraint(['workflow_node_id'], ['workflow_nodes.id'], name=op.f('fk_pr_review_runs_workflow_node_id_workflow_nodes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pr_review_runs'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pr_review_runs')
    # ### end Alembic commands ###
